In [1]:
import re
import html
import datetime 
import pandas as pd 
import requests 
from bs4 import BeautifulSoup 
import random

HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
             'cookie': 'over18=1;'}

In [2]:
def cakeresume_webCrawl(pages):

    job_title = []
    company_name = []
    job_description = []
    address = []
    money = []
    level = []
    chances = []
    updates = []
    experience = []
    management = []
    trade = []
    duty = []
    job_skill = []
    
    #URL = 'https://www.cakeresume.com/jobs?location_list%5B0%5D=Taiwan&job_type%5B0%5D=full_time'
    URL = 'https://www.cakeresume.com/jobs?location_list%5B0%5D=Taiwan&profession%5B0%5D=it_python-developer&profession%5B1%5D=it_big-data-engineer&profession%5B2%5D=it_bi-engineer&profession%5B3%5D=it_data-scientist&profession%5B4%5D=it_machine-learning-engineer&profession%5B5%5D=it_data-engineer'
    
    r = requests.get(URL, headers=HEADERS)
    r.encoding = 'utf-8' #轉換編碼至UTF-8
    soup = BeautifulSoup(r.text)

    jobTitle = soup.select("a[class='JobSearchItem_jobTitle__Fjzv2']")
    companyName = soup.select("a[class='JobSearchItem_companyName__QKkj5']")
    jobDescription = soup.select("div[class='JobSearchItem_description__tNSbN']")
    workcity = soup.select("div[class='JobSearchItem_featureSegments__I1Csc']")
    #salary = soup.select("div[class='InlineMessage_label__hP3Fk']")
    item = soup.select("div[class='JobSearchItem_features__G8vxl']") #Breadcrumbs_labelText__LW0fe

    for i in item:
        iii = i.find('div','InlineMessage_label__hP3Fk')
        temp = iii.text.split('・') # 工作機會數, 全職兼職, 經驗需求
        chances.append(temp[0])
        level.append(temp[2])


    for i in range(len(jobTitle)):
        job_title.append(jobTitle[i].text)
        company_name.append(companyName[i].text)
        job_description.append(jobDescription[i].text)
        
        try:
            address.append(workcity[i*2+1].text)
        except:
            address.append('-')
        
            
        r = requests.get('https://www.cakeresume.com'+jobTitle[i]['href'], headers=HEADERS)
        r.encoding = 'utf-8' #轉換編碼至UTF-8
        soup = BeautifulSoup(r.text)

        items = soup.select("div[class='JobDescriptionRightColumn_row__uGTdT']")
        updates_one = soup.find('div','InlineMessage_label__hP3Fk')

        updates.append(updates_one.text)

        trade_duty = soup.select("span[class='Breadcrumbs_labelText__LW0fe']")
        trade.append(trade_duty[3].text)
        duty.append(trade_duty[4].text)

        judge = ''
        for i in items:
            Text = i.text
            judge+=Text

            if 'TWD' in Text or 'NT' in Text or 'K+ null' in Text:
                money.append(Text)

            elif 'experience' in Text or '工作經驗' in Text:
                experience.append(Text)

            elif 'Managing' in Text or '管理' in Text:
                management.append(Text)

        if 'experience' not in judge and '工作經驗' not in judge:
            experience.append('-')

        if 'Managing' not in judge and '管理' not in judge:
            management.append('-')


        jobSkill = soup.select("div[class='RailsHtml_container__VVQ7u']")
        job_skill.append(jobSkill[1].text)
        
    
    for p in range(2, pages+1):
        #url = f'https://www.cakeresume.com/jobs?location_list%5B0%5D=Taiwan&job_type%5B0%5D=full_time&page={p}'
        url = f'https://www.cakeresume.com/jobs?location_list%5B0%5D=Taiwan&profession%5B0%5D=it_python-developer&profession%5B1%5D=it_big-data-engineer&profession%5B2%5D=it_bi-engineer&profession%5B3%5D=it_data-scientist&profession%5B4%5D=it_machine-learning-engineer&profession%5B5%5D=it_data-engineer&page={p}'
        r = requests.get(url, headers=HEADERS)
        r.encoding = 'utf-8' #轉換編碼至UTF-8
        soup = BeautifulSoup(r.text)

        jobTitle = soup.select("a[class='JobSearchItem_jobTitle__Fjzv2']")
        companyName = soup.select("a[class='JobSearchItem_companyName__QKkj5']")
        jobDescription = soup.select("div[class='JobSearchItem_description__tNSbN']")
        workcity = soup.select("div[class='JobSearchItem_featureSegments__I1Csc']")
        item = soup.select("div[class='JobSearchItem_features__G8vxl']") #Breadcrumbs_labelText__LW0fe

        for i in item:
            iii = i.find('div','InlineMessage_label__hP3Fk')
            temp = iii.text.split('・') # 工作機會數, 全職兼職, 經驗需求
            chances.append(temp[0])
            level.append(temp[2])


        for i in range(len(jobTitle)):
            job_title.append(jobTitle[i].text)
            company_name.append(companyName[i].text)
            job_description.append(jobDescription[i].text)
            
            try:
                address.append(workcity[i*2+1].text)
            except:
                address.append('-')



            r = requests.get('https://www.cakeresume.com'+jobTitle[i]['href'], headers=HEADERS)
            r.encoding = 'utf-8' #轉換編碼至UTF-8
            soup = BeautifulSoup(r.text)

            items = soup.select("div[class='JobDescriptionRightColumn_row__uGTdT']")
            updates_one = soup.find('div','InlineMessage_label__hP3Fk')

            updates.append(updates_one.text)

            trade_duty = soup.select("span[class='Breadcrumbs_labelText__LW0fe']")
            trade.append(trade_duty[3].text)
            duty.append(trade_duty[4].text)

            judge = ''
            for i in items:
                Text = i.text
                judge+=Text

                if 'TWD' in Text or 'NT' in Text or 'K+ null' in Text:
                    money.append(Text)

                elif 'experience' in Text or '工作經驗' in Text:
                    experience.append(Text)

                elif 'Managing' in Text or '管理' in Text:
                    management.append(Text)

            if 'experience' not in judge and '工作經驗' not in judge:
                experience.append('-')

            if 'Managing' not in judge and '管理' not in judge:
                management.append('-')


            jobSkill = soup.select("div[class='RailsHtml_container__VVQ7u']")
            job_skill.append(jobSkill[1].text)
        
        
    
    jobs = pd.DataFrame()

    # 欄位： 職缺內容, 公司名稱, 地址, 薪資, 網址, 應徵人數
    jobs['職稱']=job_title
    jobs['公司名稱']=company_name
    jobs['職缺描述']=job_description
    jobs['職缺需求']=job_skill
    jobs['地址']=address
    jobs['薪資']=money
    jobs['所需人數']=chances
    jobs['更新時間']=updates
    jobs['職等']=level
    jobs['工作經驗要求']=experience
    jobs['管理責任要求']=management
    jobs['產業']=trade
    jobs['職務']=duty
    
    jobs['職缺描述'] = jobs['職缺描述'].str.replace('\n', '')
    jobs['職缺需求'] = jobs['職缺需求'].str.replace('\n', '')
    
    return jobs


    
#print(len(jobTitle),len(companyName),len(workcity),len(salary),len(views))
    
#print(len(job_title),len(company_name),len(address),len(money),len(chances),len(job_description_site))

In [3]:
test = cakeresume_webCrawl(26)
test

,職稱,公司名稱,職缺描述,職缺需求,地址,薪資,所需人數,更新時間,職等,工作經驗要求,管理責任要求,產業,職務
0,【採線上面談】Data Analyst 資料分析師,新加坡商鈦坦科技,"【Game changer, armed with data.】 You know all ...",【What we are looking for in a Data Analyst】1. ...,115台灣台北市南港區,"50,000 ~ 90,000 TWD / 月",1,職缺 22 天前更新,初階,-,-,軟體,數據工程師
1,🏥國際型醫療AI新創🫲 -(部分遠端)Senior Backend Engineer (Py...,CakeResume Headhunting Recruitment Service,公司介紹：運用人工智慧實現精準醫療的尖端， 公司致力於提供病理數位轉型及人工智慧輔助診斷之解...,必備：1.具備兩年以上相關經驗2.熟悉 Linux 操作及 Python，具備使用 Pyth...,115台灣台北市南港區,"1,200,000 ~ 1,800,000 TWD / 年",3,職缺 2 天前更新,初階,需具備 3 年以上工作經驗,-,軟體,Python 開發人員
2,SEO consultant intern（SEO行銷顧問實習生）,零一成長行銷有限公司,大家好！我們是 零一成長行銷公司 歡迎加入我們目前團隊的開發部隊，團隊 未來即將部屬不同跨領...,我們正在尋找一名具有行銷策略思維與SEO基礎了解的實習生加入我們的團隊。作為實習生，您將會與...,100台灣台北市中正區,180 ~ 250 TWD / 月,1,職缺大約 1 個月前更新,實習,-,-,軟體,機器學習工程師
3,AI Software Development Engineer,肯狄科研有限公司,"At MAI, our mission is to revolutionize the wa...",A minimum of 5 years of commercial application...,台灣台北,"120,000 ~ 160,000 TWD / 月",2,職缺大約 17 小時前更新,中高階,需具備 5 年以上工作經驗,-,軟體,機器學習工程師
4,【採線上面談】Data Engineer 資料工程師,新加坡商鈦坦科技,【Job Responsabilities】 ・Create and maintain op...,鈦坦科技，是一間總部位於新加坡的軟體開發公司，提供線上軟體平台客製開發與維護，以及代理 At...,115台灣台北市南港區,"50,000 ~ 90,000 TWD / 月",1,職缺大約 1 個月前更新,初階,-,-,軟體,數據工程師
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,語音識別演算法工程師,易晨智能,工作說明 1. 負責語音辨識聲學模型，語言模型訓練。 2. 善於語音識別處理業界最新動態、實...,易晨智能股份有限公司創立於2019年中，團隊核心技術具有語音辨識演算法，自然語言理解演算法，...,新北市三重區,"45,000 ~ 60,000 TWD / 月",1,職缺將近 2 年前更新,初階,-,-,軟體,數據科學家
219,軟體設計工程師,大門科技顧問公司,【工作說明】 1. 資歷搜集及分析。 2. 負責各項策略分析及回測研究。 3. 量化交易系統...,【建議條件】1. 掌握C++/Golang/php2. 熟悉網路程式設計、資料結構和加密演算...,"Lingya District, Kaohsiung City, Taiwan 802","42,000 ~ 60,000 TWD / 月",3,職缺將近 2 年前更新,初階,-,-,軟體,數據工程師
220,大數據研發工程師聘用,金微科技股份有限公司,[主要職務內容] 依據專案需求進行商業理解、數據理解、以及數據準備。 數據品質評估 數據清洗...,"[需求條件]python, numpy, scipy, pandas, sklearn, s...",台北市,"40,000 ~ 100,000 TWD / 月",5,職缺將近 3 年前更新,中高階,-,-,軟體,數據工程師
221,32000-AI智慧工程師,QNAP Systems,數位轉型MarTech/SerTech/SaleTech、網路商城、公司內部服務等智慧功能開發,"1. 熟悉Python, Dialogflow等相關平台2. 熟於AI演算法與應用框架3. ...",新北・汐止區・中興路,"38,000 ~ 65,000 TWD / 月",1,職缺大約 3 年前更新,中高階,-,-,軟體,數據工程師
222,Spark Taiwan生醫轉譯加值人才培育碩士級以上職務代理人10860,國家實驗研究院科技政策研究與資訊中心,1.執行生醫與醫材轉譯加值人才培訓計畫相關業務，扶植台灣生醫新創團隊 2.協助計畫相關之管考...,接受身份：上班族工作經歷：不拘學歷要求：碩士以上科系要求：不拘語文條件：英文 -- 聽 /精...,大安區・科技大樓站・台北,"40,000+ TWD / 月",1,職缺將近 4 年前更新,助理,-,-,軟體,數據工程師

In [8]:
#category_counts = test['職務'].value_counts()
category_counts = new_demand['職務'].value_counts()
category_counts

資料工程師     89
資料科學家     44
AI工程師     41
演算法工程師    37
數據分析師     12
Name: 職務, dtype: int64

In [6]:
# 中英分離

demand = test.filter(['職稱','職務','職缺描述'])

# 创建一个新的DataFrame来存放拆分后的行
new_rows = []

# 遍历原始DataFrame
for index, row in demand.iterrows():
    job_titles = row['職務'].split('、')
    jobName = row['職稱']
    JD = row['職缺描述']
    for title in job_titles:
        new_row = {'職務': title, '職稱': jobName, '職缺描述':JD}
        new_rows.append(new_row)

# 创建包含新行的新DataFrame
new_demand = pd.DataFrame(new_rows)

# data_duty = ['數據分析師','資料科學家','資料工程師','AI工程師','演算法工程師']
# mask = new_demand['職務'].isin(data_duty)
# new_demand = new_demand[mask]

# 將 工作敘述 的網址取代掉
def remove_url_and_html(text):
    # 用 re 取代 URL
    text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', text)
    
    # 用 re 移除 HTML tag
    text = re.sub(r'<.*?>', '', text)
    text = text.replace('\n', '').replace('\r', '').replace('\t', '')
    
    return text

# use re to replace html entities
def replace_html_entities(text):
    
    text = re.sub(r'<.*?>', '', text)
    
    # parse entities
    text = html.unescape(text)
    
    return text

new_demand['職缺描述'] = new_demand['職缺描述'].apply(remove_url_and_html)
new_demand['職缺描述'] = new_demand['職缺描述'].apply(replace_html_entities)

# 中英文 分離
# 提取中文
def extract_chinese(text):
    chinese_pattern = r'[\u4e00-\u9fa5]+'  # 中文字符
    chinese_matches = re.findall(chinese_pattern, text)
    return ' '.join(chinese_matches)  # 將多個中文字符，以空格分隔

# 提取英文
def extract_english(text):
    english_pattern = r'[a-zA-Z]+'  # 英文字符
    english_matches = re.findall(english_pattern, text)
    return ' '.join(english_matches)  # 將多個英文字符，以空格分隔

new_demand['職缺描述（中文）'] = new_demand['職缺描述'].apply(extract_chinese)
new_demand['職缺描述（英文）'] = new_demand['職缺描述'].apply(extract_english)

new_demand

,職務,職稱,職缺描述,職缺描述（中文）,職缺描述（英文）
0,數據工程師,【採線上面談】Data Analyst 資料分析師,"【Game changer, armed with data.】 You know all ...",,Game changer armed with data You know all abou...
1,Python 開發人員,🏥國際型醫療AI新創🫲 -(部分遠端)Senior Backend Engineer (Py...,公司介紹：運用人工智慧實現精準醫療的尖端， 公司致力於提供病理數位轉型及人工智慧輔助診斷之解...,公司介紹 運用人工智慧實現精準醫療的尖端 公司致力於提供病理數位轉型及人工智慧輔助診斷之解決...,AI CV JD AI AI Docker Compose Kubernetes
2,機器學習工程師,SEO consultant intern（SEO行銷顧問實習生）,大家好！我們是 零一成長行銷公司 歡迎加入我們目前團隊的開發部隊，團隊 未來即將部屬不同跨領...,大家好 我們是 零一成長行銷公司 歡迎加入我們目前團隊的開發部隊 團隊 未來即將部屬不同跨領...,SEO ML AI SEO PM dcard L oreal Google
3,機器學習工程師,AI Software Development Engineer,"At MAI, our mission is to revolutionize the wa...",,At MAI our mission is to revolutionize the way...
4,數據工程師,【採線上面談】Data Engineer 資料工程師,【Job Responsabilities】 ・Create and maintain op...,,Job Responsabilities Create and maintain optim...
...,...,...,...,...,...
218,數據科學家,語音識別演算法工程師,工作說明 1. 負責語音辨識聲學模型，語言模型訓練。 2. 善於語音識別處理業界最新動態、實...,工作說明 負責語音辨識聲學模型 語言模型訓練 善於語音識別處理業界最新動態 實驗業界最新研究...,NLP HTK kaldi
219,數據工程師,軟體設計工程師,【工作說明】 1. 資歷搜集及分析。 2. 負責各項策略分析及回測研究。 3. 量化交易系統...,工作說明 資歷搜集及分析 負責各項策略分析及回測研究 量化交易系統介面 功能模組的開發及維運...,
220,數據工程師,大數據研發工程師聘用,[主要職務內容] 依據專案需求進行商業理解、數據理解、以及數據準備。 數據品質評估 數據清洗...,主要職務內容 依據專案需求進行商業理解 數據理解 以及數據準備 數據品質評估 數據清洗 依 ...,ETL Extract Transform Load
221,數據工程師,32000-AI智慧工程師,數位轉型MarTech/SerTech/SaleTech、網路商城、公司內部服務等智慧功能開發,數位轉型 網路商城 公司內部服務等智慧功能開發,MarTech SerTech SaleTech
222,數據工程師,Spark Taiwan生醫轉譯加值人才培育碩士級以上職務代理人10860,1.執行生醫與醫材轉譯加值人才培訓計畫相關業務，扶植台灣生醫新創團隊 2.協助計畫相關之管考...,執行生醫與醫材轉譯加值人才培訓計畫相關業務 扶植台灣生醫新創團隊 協助計畫相關之管考 業務與...,

In [7]:
new_demand['職務'] = new_demand['職務'].str.replace('數據','資料')
new_demand['職務'] = new_demand['職務'].str.replace('機器學習','AI')
new_demand['職務'] = new_demand['職務'].str.replace('BI 開發人員','數據分析師')
new_demand['職務'] = new_demand['職務'].str.replace('大資料開發人員','數據分析師')
new_demand['職務'] = new_demand['職務'].str.replace('Python 開發人員','演算法工程師')
new_demand

,職務,職稱,職缺描述,職缺描述（中文）,職缺描述（英文）
0,資料工程師,【採線上面談】Data Analyst 資料分析師,"【Game changer, armed with data.】 You know all ...",,Game changer armed with data You know all abou...
1,演算法工程師,🏥國際型醫療AI新創🫲 -(部分遠端)Senior Backend Engineer (Py...,公司介紹：運用人工智慧實現精準醫療的尖端， 公司致力於提供病理數位轉型及人工智慧輔助診斷之解...,公司介紹 運用人工智慧實現精準醫療的尖端 公司致力於提供病理數位轉型及人工智慧輔助診斷之解決...,AI CV JD AI AI Docker Compose Kubernetes
2,AI工程師,SEO consultant intern（SEO行銷顧問實習生）,大家好！我們是 零一成長行銷公司 歡迎加入我們目前團隊的開發部隊，團隊 未來即將部屬不同跨領...,大家好 我們是 零一成長行銷公司 歡迎加入我們目前團隊的開發部隊 團隊 未來即將部屬不同跨領...,SEO ML AI SEO PM dcard L oreal Google
3,AI工程師,AI Software Development Engineer,"At MAI, our mission is to revolutionize the wa...",,At MAI our mission is to revolutionize the way...
4,資料工程師,【採線上面談】Data Engineer 資料工程師,【Job Responsabilities】 ・Create and maintain op...,,Job Responsabilities Create and maintain optim...
...,...,...,...,...,...
218,資料科學家,語音識別演算法工程師,工作說明 1. 負責語音辨識聲學模型，語言模型訓練。 2. 善於語音識別處理業界最新動態、實...,工作說明 負責語音辨識聲學模型 語言模型訓練 善於語音識別處理業界最新動態 實驗業界最新研究...,NLP HTK kaldi
219,資料工程師,軟體設計工程師,【工作說明】 1. 資歷搜集及分析。 2. 負責各項策略分析及回測研究。 3. 量化交易系統...,工作說明 資歷搜集及分析 負責各項策略分析及回測研究 量化交易系統介面 功能模組的開發及維運...,
220,資料工程師,大數據研發工程師聘用,[主要職務內容] 依據專案需求進行商業理解、數據理解、以及數據準備。 數據品質評估 數據清洗...,主要職務內容 依據專案需求進行商業理解 數據理解 以及數據準備 數據品質評估 數據清洗 依 ...,ETL Extract Transform Load
221,資料工程師,32000-AI智慧工程師,數位轉型MarTech/SerTech/SaleTech、網路商城、公司內部服務等智慧功能開發,數位轉型 網路商城 公司內部服務等智慧功能開發,MarTech SerTech SaleTech
222,資料工程師,Spark Taiwan生醫轉譯加值人才培育碩士級以上職務代理人10860,1.執行生醫與醫材轉譯加值人才培訓計畫相關業務，扶植台灣生醫新創團隊 2.協助計畫相關之管考...,執行生醫與醫材轉譯加值人才培訓計畫相關業務 扶植台灣生醫新創團隊 協助計畫相關之管考 業務與...,

In [9]:
new_demand.to_excel('CakeResume數據職缺JD_中英文分離_1004.xlsx', index=False)

In [ ]:
# colab settings

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
cd /content/gdrive/My Drive/Colab Notebooks/WebCrawl

/content/gdrive/My Drive/Colab Notebooks/WebCrawl

In [ ]:
test.to_excel('CakeResume_jobs.xlsx',index=False)