In [1]:
import re
import json
import html
import datetime 
import requests
import pandas as pd 
import urllib.request
from bs4 import BeautifulSoup


HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
             'cookie': 'over18=1;'}

In [2]:
# 'https://www.yourator.co/companies/mexcglobal/jobs/26192'

def get_job_detail(url_jobID):#='https://www.yourator.co/companies/PicCollage/jobs/10227'): 

    r = requests.get(url_jobID, headers=HEADERS)
    r.encoding = 'utf-8' #轉換編碼至UTF-8
    soup = BeautifulSoup(r.text)
    
    # 工作內容 條件要求 
    judge = soup.select("div[class='col-md-9 col-sm-12 job__content']")
    
#     job_content=[]
#     job_requirement=[]
    for i in range(len(judge)):
        Text = judge[i].text
        
        if '遠端型態' in Text:
            targetText = Text.split('遠端型態')[0]
            content_requirement_split = targetText.split('條件要求')
            
        elif '加分條件' in Text:
            targetText = Text.split('加分條件')[0]
            content_requirement_split = targetText.split('條件要求')
            
        elif '員工福利' in Text:
            targetText = Text.split('員工福利')[0]
            content_requirement_split = targetText.split('條件要求')
        
        elif '薪資範圍' in Text:
            targetText = Text.split('薪資範圍')[0]
            content_requirement_split = targetText.split('條件要求')
            
        content_requirement_split[0] = content_requirement_split[0].replace('\n','')
        content_requirement_split[0] = content_requirement_split[0].replace('\xa0','')
        content_requirement_split[0] = content_requirement_split[0].replace('工作內容','')
        jobContent = content_requirement_split[0]
        if content_requirement_split[1]!='\n\n':
            content_requirement_split[1] = content_requirement_split[1].replace('\n','')
            content_requirement_split[1] = content_requirement_split[1].replace('\xa0','')
            jobRequirement = content_requirement_split[1]
        else:
            jobRequirement = '-'
        
    return jobContent, jobRequirement
        
        
#get_job_detail()

In [3]:
# 欄位： 職缺內容, 公司名稱, 地址, 薪資, 網址, 應徵人數
# https://www.yourator.co/api/v2/job_categories
# https://www.yourator.co/api/v3/job_areas
# https://www.yourator.co/api/v2/jobs?position[]=full_time&sort=recent_updated&page=3

# 全職 最近更新時間
# URL = 'https://www.yourator.co/jobs?position[]=full_time&sort=newest'

# url_page = 'https://www.yourator.co/api/v2/jobs?position[]=full_time&sort=recent_updated&page=2'

def webCrawl_Yourator(pages):

    # columns
    job_title = []
    company_name = []
    address = []
    money = []
    job_content = []
    job_requirement = []
    trade = []
    tags = []
    job_detail_url = []

    url_page = f'https://www.yourator.co/api/v4/jobs?category[]=%E8%B3%87%E6%96%99%E5%B7%A5%E7%A8%8B%20%2F%20%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92&page=1&sort=recent_updated'
    #url_page = f'https://www.yourator.co/api/v2/jobs?position[]=full_time&sort=recent_updated'
    r = urllib.request.Request(url_page, headers=HEADERS)
    r = urllib.request.urlopen(r)

    soup = BeautifulSoup(r, 'html.parser')
    data = json.loads(str(soup))
    
    print(data['payload']['nextPage'], type(data['payload']['nextPage']))

    for j in data['payload']['jobs']:
        job_title.append(j['name'])
        company_name.append(j['company']['brand'])
        address.append(j['location'])
        money.append(j['salary'])
        #trade.append(j['category']['name'])
        temp = j['tags']

        if temp!=[]:
            temp = ', '.join(temp)
        else:
            temp='-'

        tags.append(temp)

        jobDetail_url = 'https://www.yourator.co'+j['path']
        
        Con, Req =  get_job_detail(jobDetail_url)
        job_content.append(Con)
        job_requirement.append(Req) 

        
    for p in range(2,pages):
        
        url_page = f'https://www.yourator.co/api/v4/jobs?category[]=%E8%B3%87%E6%96%99%E5%B7%A5%E7%A8%8B%20%2F%20%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92&page=1&sort=recent_updated&page={p}'
        #url_page = f'https://www.yourator.co/api/v2/jobs?position[]=full_time&sort=recent_updated&page={p}'
        r = urllib.request.Request(url_page, headers=HEADERS) #(url_page, headers=HEADERS)
        r = urllib.request.urlopen(r)

        soup = BeautifulSoup(r, 'html.parser')
        data = json.loads(str(soup))
        
        if data['payload']['nextPage'] != None: 
        
            print(data['payload']['nextPage'], type(data['payload']['nextPage']))

            for j in data['payload']['jobs']:
                job_title.append(j['name'])
                company_name.append(j['company']['brand'])
                address.append(j['location'])
                money.append(j['salary'])
                #trade.append(j['category']['name'])
                temp = j['tags']

                if temp!=[]:
                    temp = ', '.join(temp)
                else:
                    temp='-'

                tags.append(temp)

                jobDetail_url = 'https://www.yourator.co'+j['path']

                Con, Req =  get_job_detail(jobDetail_url)
                job_content.append(Con)
                job_requirement.append(Req) 
                
            #print('run')
                
        else:
            #print('stop')
            break

    final_df = pd.DataFrame()

    final_df['職缺名稱']=job_title
    final_df['公司名稱']=company_name
    final_df['工作內容']=job_content
    final_df['條件要求']=job_requirement
    final_df['工作地']=address
    final_df['薪資']=money
    #final_df['產業']=trade
    final_df['標籤']=tags

    return final_df

In [4]:
test = webCrawl_Yourator(7)
test

2 <class 'int'>
3 <class 'int'>
4 <class 'int'>

,職缺名稱,公司名稱,工作內容,條件要求,工作地,薪資,標籤
0,資料科學家,友達耘康股份有限公司,中醫只有華人才能精確掌握，雖然目前還很低調，但我們能提供的產品價值是過往廠商都無法提供的。除...,1.統計系畢業或具相關經驗2.具閱讀國外期刊及論文之能力3.熟悉模型開發流程（MLOps）4...,新竹市,面議（經常性薪資達4萬元）,"AI, Data Scientist, Statistics Analysis"
1,[總部] 機器學習主任工程師 Principal Engineer_0220*,Gamania 橘子集團,我們是集團的策略長室團隊，目前正在積極尋找Machine Learning 主任工程師 加入...,▍你需具有1.有 AI/ML 研發能力2.有 AI/ML 專案經驗3.優秀的溝通與團隊合作能...,臺北市,"NT$ 1,000,000 - 1,800,000 (年薪)","軟體開發, AI, 軟體設計工程師, 機器學習, 大數據, 演算法開發工程師"
2,Backend Engineer (Python),Dcard,【Please Apply Here】https://grnh.se/3f28ec0f1us...,We are looking for an excellent Backend Engine...,臺北市,面議（經常性薪資達4萬元）,-
3,AI 產品經理( Prompt Engineering/ Fine Tuning）,肖準行銷,部門介紹The Pocket CompanyThe Pocket Company是Accuc...,本科以上學位，資訊管理、資訊工程或相關專業優先考慮。擁有AI 產品經理或相關職位工作經驗，有...,臺北市,"NT$ 38,000 - 80,000 (月薪)",-
4,Data Engineer - Python,CTW株式会社,作為數據工程師（Python），您將負責在我們的G123平台上設計和實施強大的數據流程，以確...,- 計算機科學或其他相關領域的學士學位或以上學歷- 3年以上相關數據工程等經驗- 熟練掌握：...,臺北市,"NT$ 1,000,000 - (年薪)",Data Engineer
5,NLP Research Scientist,CTW株式会社,作為自然語言處理（NLP）研究技術人員，您將負責在與工程團隊密切合作的同時實施自然語言處理技...,- 在機器翻譯、自然語言生成、文本摘要、對話系統、問答等領域具有研究/行業經驗- 出色的分析...,臺北市,"NT$ 1,000,000 - (年薪)",NLP
6,MLOps Engineer,CTW株式会社,作為機器學習運維（MLOps）工程師，您將負責實現模型在生產系統中的自動化部署，以在G123...,在Python方面有可驗證的熟練技能熟練使用AWS及其服務，如SageMaker、EC2、E...,臺北市,"NT$ 1,000,000 - (年薪)",MachineLearning
7,Data Scientist,CTW株式会社,作為數據科學家，您將負責基於我們的G123平台大數據，應用機器學習、統計分析和數據可視化技術...,- 在統計分析、機器學習、自然語言處理（NLP）、推薦系統、自動化等相關領域具有經驗- 出色...,臺北市,"NT$ 1,000,000 - (年薪)",data s
8,Prompt Engineer,CTW株式会社,- 與人工智慧和數據科學團隊緊密合作，為AI語言模型（如GPT-4）或生成式AI模型（如St...,- 計算機科學、數據科學、語言學或相關領域的學士及以上學位- 有使用AI語言模型（如GPT-...,臺北市,"NT$ 1,000,000 - (年薪)",Prompt
9,CV Research Scientist,CTW株式会社,作為計算機視覺研究技術人員，您將負責在我們的內部橫幅生成工具中實現諸如GAN或穩定擴散等新的...,- 在圖像生成（GAN/穩定擴散）、神經圖像評估、物體檢測、圖像識別或類似領域具有研究/行業...,臺北市,"NT$ 1,000,000 - (年薪)",ComputerVision
10,【R&D】資料科學工程師 (AI),奧丁丁集團（英屬開曼群島商台灣子公司-歐簿客科技）,1. 基於LLMs開發應用及聊天功能，設計並優化體驗內容2. 機器學習、深度學習或其他資料科...,1. 熟悉AI chatbot、LLMs相關知識2. 熟悉機器學習、深度學習理論及相關開發經...,新北市,"NT$ 40,000 - 100,000 (月薪)","AI, Data Scientist, Data, 資料科學"
11,2023 Turing Plan 儲備AI科學家 百萬年薪 開放申請中！,永豐金控 Sinopac Holdings,【你的薪資你決定，百萬Turing就是你】Turing Plan 矢志尋找最頂尖的人工智慧技...,1.電機/資工/機械/數學/統計相關系所，具軟體工程、人工智慧、資料科學、資料工程等經驗，無...,臺北市,"NT$ 1,000,000 - (年薪)","Python, AI, 人工智慧, 演算法開發工程師, 資料工程, 資料科學家"
12,Video/ Image Processing Engineer,PicCollage 拼貼趣,We are looking for a Video/Image Processing So...,Requirements:At least 3 years of work experien...,臺北市,"NT$ 1,600,000 - 2,500,000 (年薪)","跨國團隊, APP, 設計產業, 文創"
13,MLOps Engineer,PicCollage 拼貼趣,"As a MLOps engineer, you will be responsible f...","Responsibilities:Design, build and maintain da...",臺北市,"NT$ 1,700,000 - 3,000,000 (年薪)","Python, MachineLearning, pytorch, tensorflow, ..."
14,【AI Team】資料科學家 Data Scientist,iKala 愛卡拉,【Responsibilities】 1. Plan actionable research...,"【Requirements】 1. Degree in business, economic...",臺北市,面議（經常性薪資達4萬元）,"Python, SQL, Data Scientist, DS"
15,數據架構師 Data Architect,WebComm 偉康科技,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,"具二年以上數據專案或產品的架構設計實務經驗。具程式設計（python, java, node...",臺北市,面議（經常性薪資達4萬元）,Data
16,BI Analyst_BI數據分析,OpenNet,"- Set up and execute extract, transformation a...",Requirements●Proactive and self-driven with ex...,臺北市,"NT$ 910,000 - 1,800,000 (年薪)","資訊平台, 遊戲產業, 網路"
17,深度(機器)學習資料科學家(台中),慧穩科技,1. 深度學習資料分析運用於機器視覺2. 深度學習演算法研究3. 資料前處理：確認客戶需求及...,擅長工具1、Linux2、C3、C#4、C++5、Python,臺中市,面議（經常性薪資達4萬元）,"軟體設計工程師, 演算法開發工程師, 統計學研究員, 3年以上工作經驗, 學歷碩士"
18,Data Scientist,BlueX,"About The Job:At BlueX, data drives our decisi...",Bachelor's degree in a quantitative discipline...,臺北市,面議（經常性薪資達4萬元）,"MachineLearning, Data Scientist, ETL"
19,AI/CV Team Lead /Sr. Computer Vision Engineer ...,Authme 數位身分股份有限公司,世界上沒有一個模型不能解決的問題。 如果有，那就再做一個。Authme 致力於提供最快速、安...,條件需求資工、電機或相關領域之學士、碩士、博士具備5年以上電腦視覺與深度學習領域的工作經驗，...,臺北市,"NT$ 1,800,000 - 2,500,000 (年薪)","新創, Python, 網路新創, 網路, C++"
20,【AI Team】資深數據工程師 Senior Data Engineer,iKala 愛卡拉,【Responsibilities】1. Create and maintain optim...,【Requirements】1. Experience with Computer Scie...,臺北市,面議（經常性薪資達4萬元）,Data Engineer
21,DBA資料庫管理師 (MSSQL/MySQL),街口支付,KeyResponsibilities1. Troubleshoot application...,Basic Qualifications (required)1. Excellent or...,臺北市,"NT$ 900,000 - 1,300,000 (年薪)","Fintech, MySQL, 行動支付, MsSQL, DBA"
22,【TENG1402】Data Engineer,"SHOPLINE Technology Corp., Ltd.",At SHOPLINE we are working on very interesting...,【Who we are looking for】- Fluent in Python and...,臺北市,面議（經常性薪資達4萬元）,"SaaS, Data Engineer, ecommerce"
23,資深數據工程師 Senior Data Engineer,WebComm 偉康科技,我們是偉康科技智能團隊，專注解決金融領域的智能專家，持續精進並發展監理科技產品。團隊成員有智...,▍須具備之知識範疇1. 數據軟硬體機容評估、配置及佈署圖。2. 數據軟體問題排除及效能調校。...,臺北市,面議（經常性薪資達4萬元）,Data Engineer
24,數據解決方案架構師 Data Solution Architect,WebComm 偉康科技,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,具二年以上數據解決方案售前經驗。熟悉任一套資料產品。善於簡報及知識分享、擅長團隊合作者。主動...,臺北市,面議（經常性薪資達4萬元）,-
25,Machine Learning intern,慧景科技thingnario,了解各IoT領域（太陽能、射出成型機、電腦數值控制工具機 等等）的痛點，應用 ＭＬ以最有效率...,【必要條件】樂觀開心、有話直說、充滿好奇心、勇於接受挑戰、勇敢負責承擔資工相關領域的大四、碩...,臺北市,NT$ 250 - (時薪),"新創, Python, 軟體開發, AI, MachineLearning, DeepLea..."
26,系統分析師 System Analyst - Salesforce,綠色和平 Greenpeace,Greenpeace exists because this fragile earth d...,QUALIFICATIONSDegree in information technology...,臺北市,"NT$ 58,000 - (月薪)","系統分析師, data analysis, System analysis, System ..."
27,AI工程師(街口金融科技),街口支付,街口集團旗下新創事業，致力於打造AI驅動的社交App，我們正在積極尋找有熱情的夥伴加入團隊，...,【Qualification】1. 資訊工程、計算機科學相關系所，學士或碩士學歷。2. 熟悉...,臺北市,面議（經常性薪資達4萬元）,"Python, MachineLearning, DeepLearning, Convers..."
28,生物資訊工程師,Vizuro 維曙智能科技,作為生物資訊工程師，除熟悉組學資料處理分析外，應時時渴望新技術與知識，與AI團隊協作發展出獨...,基本需求A Bachelor's or Master's degree in bioinfo...,臺北市,"NT$ 800,000 - 1,300,000 (年薪)","AI, MachineLearning, Drug Discovery, Causal In..."
29,資料科學家 Data Scientist,Vizuro 維曙智能科技,作為資料科學家，需要對資料保有高度熱誠，能夠歸納與統整大量的資料，並從中萃取出精華，發現未察...,技能需求良好的溝通技巧期刊論文閱讀與報告能力基礎程式能力。如Python、R語言資料處理能力...,臺北市,"NT$ 800,000 - 1,300,000 (年薪)","AI, MachineLearning, DeepLearning, Drug Discov..."
30,台灣領頭自駕系統軟體新創 Senior Algorithm Engineer (SLAM),JobMenta by Yourator 中高階獵才,[About the role]We are looking for a talented ...,[Minimum Qualifications]MS or Ph.D. in Compute...,臺北市,面議（經常性薪資達4萬元）,-
31,Data Engineer 資料工程師,GoFreight,GoFreight 是快速成長的雲端國際物流 SaaS 新創公司，專注在利用科技翻轉國際物流...,具備 3 年以上相關經驗資訊、統計等工程或數學相關科系學士以上學歷有程式開發經驗 (Pyth...,臺北市,面議（經常性薪資達4萬元）,-
32,數據工程師,Aloha Group,工作地點:台北 + 遠端🇹🇼+🏡想要在職業生涯中快速發展？不要找工作！選擇一家公司，釋放你的...,良好MySQL及SQL技巧，並有1年以上大數據處理相關工作經驗有Data Pipeline，...,臺北市,"NT$ 40,000 - 55,000 (月薪)","Data Engineer, 數據工程師"
33,"資深數據工程師 Sr.Data Engineer (AI Team, 台北/嘉義/東京)",awoo,awoo 株式會社 (awoo Japan Inc.) 的成員來自世界各地，我們正在招募對深...,Qualifications：1.實際參與大量數據清處理或大型系統實戰經驗2.實際參與 CI...,臺北市,面議（經常性薪資達4萬元）,"Python, BigData, Linux, GCP, kubernetes, K8s"
34,AI / 機器學習工程師,Vizuro 維曙智能科技,作為AI/機器學習工程師，須掌握各式的AI技術，並提供穩定且可靠的AI模型給使用者，也應隨時...,技能需求期刊論文閱讀能力熟悉以下任一框架 ：Tensorflow、Pytorch、JAX熟悉...,臺北市,"NT$ 800,000 - 1,300,000 (年薪)","Python, AI, MachineLearning, DeepLearning"
35,Data Scientist,雲象科技 aetherAI,"1. Design, develop and implement machine learn...",1. 3 years of experience in computer vision in...,臺北市,面議（經常性薪資達4萬元）,"Python, AI, Linux, MachineLearning, Data Scien..."
36,Senior Machine Learning Engineer,雲象科技 aetherAI,"1. Design, develop and implement machine learn...",1. 2 years of experience in computer vision in...,臺北市,面議（經常性薪資達4萬元）,"Python, AI, BigData, MachineLearning, DeepLear..."
37,Senior Machine Learning Engineer 資深機器學習工程師,AlfredCamera 阿福管家,"▍About AlfredCameraFrom day one, we’ve been gu...",A profound background in machine learning and ...,臺北市,"NT$ 1,200,000 - 2,000,000 (年薪)",-
38,Data Engineer｜資料工程師,街口支付,◆THE ROLE & THE TEAMAs a Data Engineer in JKOP...,◆WE'D LOVE TO MEET YOU IF-At least 2 years of ...,臺北市,面議（經常性薪資達4萬元）,"Data Engineer, data analysis, System analysis"
39,(2023實習) Machine Learning Engineer (時薪260）(可視訊...,NETBASE QUID,***歡迎身心障礙朋友投遞履歷***NetBase Quid is searching fo...,**Requirements*** At least 6 months commitment...,臺北市,NT$ 230 - (時薪),"Python, AI, Java, BigData, MachineLearning"
40,資料科學工程師 (Kubernetes K8s 平台產品開發) -- 資料科學實驗室 (數...,國泰金控 Cathay Financial Holdings,我們 資料科學實驗室 的文化- 我們樂於互相分享，也樂於互相學習- 我們有主動發現問題，主動...,[ 必要條件 ]具備 Kubernetes 及 container 相關經驗具備 Linux...,臺北市,面議（經常性薪資達4萬元）,"Git, K8s, Python Developer, R&D, openshift, ku..."
41,"資料科學工程師 (Data Engineer) -- 資料科學實驗室 (數數發中心, DDT)",國泰金控 Cathay Financial Holdings,職務包含但不限於以下內容- 基於 Python 語言之產品開發，推廣及後續維護- Docke...,[ 必要條件 ]具備 Python 軟體開發經驗或數據處理經驗具備 Linux 系統的基礎知...,臺北市,面議（經常性薪資達4萬元）,-
42,【跨境電商物流系統】AI Engineer/ AI 工程師,香港商線上科技銷售服務有限公司台灣分公司,【職務情況說明】Return Helper為跨境電商逆物流服務商，自行開發倉儲逆物流/退貨平...,】1.Strong knowledge of Computer vision and obj...,臺北市,"NT$ 1,200,000 - 1,500,000 (年薪)","AI, MachineLearning, NLP"
43,【數位驅動】資料科學工程師_ 數據管理,國泰世華商業銀行,【主要職責 Who we are looking for】資料倉儲、資料市集設計及管理之ET...,"工作經驗:不拘學歷要求:大學以上科系要求:統計學相關,資訊管理相關,資訊工程相關語文條件英文...",臺北市,面議（經常性薪資達4萬元）,"軟體設計工程師, 其他資訊專業人員, 資料庫管理人員"
44,【運籌管理中心】MES開發工程師,O'right,1.負責生產、物流相關MES系統規劃、開發、與維護作業。2.資料分析、設計與製作相關管理報表...,•熟悉製造流程、生產管理。•具製造業MES系統開發與維護經驗3年以上(與鼎新ERP系統程式串...,桃園市,面議（經常性薪資達4萬元）,"MES, 鼎新"
45,【資通訊整合中心】ERP工程師,O'right,1.維護鼎新 COSMOS ERP系統。2.維護鼎新 EasyFlow 電子表單系統。3.開...,•五年以上專業年資。•具鼎新系統開發相關經驗。•熟悉生產製造、供應鏈、財務流程，並能架構相關...,桃園市,"NT$ 40,000 - 50,000 (月薪)","營運管理師／系統整合／ERP專案, 鼎新"
46,資料工程師 Data Engineer (台中),WeibyApps微碧愛普科技,【】與產品團隊和前後端工程團隊合作，確保資料品質與產出1. 創建與維護Data Infras...,【必備技能】1. 1年以上數據產品相關工作經驗。2. 熟悉Python。3. 具Data i...,臺中市,"NT$ 50,000 - 70,000 (月薪)",Data Engineer
47,<CCoE>Cloud Strategy Lead | CBU_13_01,eCloudvalley,【Job Description】We are EXCITED to announce th...,【Requirements】1. Bachelor's degree in any fiel...,新北市,面議（經常性薪資達4萬元）,-
48,<Data Team> Data Engineer 資料工程師| CBU_12_01,eCloudvalley,We are an ambitious Data Team Service Delivery...,【Requirements】• Bachelor's or Master's degree ...,新北市,面議（經常性薪資達4萬元）,"數據分析, Data Engineer, 資料工程"
49,<Data Team> Machine Learning Engineer 機器學習工程師...,eCloudvalley,We are an ambitious Data Team Service Delivery...,【Requirements】• Bachelor's or Master's degree ...,新北市,面議（經常性薪資達4萬元）,"MachineLearning, 機器學習"
50,香港上市醫學美容集團 AI Engineer/Specialist,JobMenta by Yourator 中高階獵才,運用Machine Learning、Deep Learning、統計與作業研究等技術來開發...,擁有相關領域的學士或碩士學位，例如計算機科學、人工智能、統計學等。至少兩年以上的AI相關領域...,臺北市,面議（經常性薪資達4萬元）,-
51,香港上市醫學美容集團 Data Engineer,JobMenta by Yourator 中高階獵才,We are currently looking to recruit an enthusi...,At least 2+ years of practical experience in D...,臺北市,面議（經常性薪資達4萬元）,-
52,107 資料分析/數據工程師(可遠端工作),台灣大哥大,聽過黑盒子、演算法、機器學習、Alphago嗎？這些讓我們聯想到AI的代名詞是否讓你躍躍欲試...,-,臺北市,"NT$ 34,000 - 60,000 (月薪)","Python, AI, SQL, Java, C#, Spark"
53,Machine Learning Engineer,玩美移動 AI/AR美妝科技,1. Use Deep Learning techniques to solve compu...,"學歷要求：碩士以上語文條件：英文 精通擅長工具：C, C++, Python",新北市,"NT$ 1,100,000 - 1,400,000 (年薪)","MachineLearning, 軟體設計工程師, pytorch, tensorflow,..."
54,數據科學家,日商卓一智能科技股份有限公司台灣分公司,我們正在和團隊成員一起開發一個系統，該系統將結合機器學習模型，自動生成用於尚平或服務廣告的文...,・擁有創建和分析機器學習模型的經驗（希望至少有2年以上的經驗）・能夠使用英語進行溝通（建議具...,臺北市,"NT$ 37,100 - 80,000 (月薪)","Data Scientist, 資料科學, 數據科學家"
55,"【數位金融】資料科學分析師-數據分析 (數數發中心,DDT)",國泰世華商業銀行,【職務說明 What will you do】1. 機器學習、深度學習或統計分析模型專案開發...,工作經驗:不拘學歷要求:研究所以上科系要求:未填寫語文條件英文(聽:中等、說:中等、讀:中等...,臺北市,面議（經常性薪資達4萬元）,"系統分析師, 演算法開發工程師, 統計學研究員"
56,【數位金融】資料營運工程師(Hadoop),國泰世華商業銀行,【主要職責 Who we are looking for】你將負責Hadoop大數據平台的運...,工作經驗:1年以上學歷要求:大學以上科系要求:未填寫語文條件英文(聽:中等、說:中等、讀:中...,臺北市,面議（經常性薪資達4萬元）,"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員"
57,【數位金融】資料營運工程師(SRE),國泰世華商業銀行,【主要職責 Who we are looking for】你將負責數據服務平台的運維工作，建...,工作經驗:2年以上學歷要求:大學以上科系要求:未填寫語文條件英文(聽:中等、說:中等、讀:中...,臺北市,面議（經常性薪資達4萬元）,"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員"
58,"【數位金融】數據策略規劃師(數數發中心, DDT)",國泰世華商業銀行,【職務說明 What will you do】1. 規劃新數據及新技術導入策略並設計對應商業...,"工作經驗3年以上學歷要求:大學以上科系要求:一般商業學類,統計學相關,其他商業及管理相關語文...",臺北市,面議（經常性薪資達4萬元）,"市場調查／市場分析, 專案管理主管, 顧問人員"
59,【數位金融】Java 開發工程師/Java Engineer(數數發中心，DDT),國泰世華商業銀行,國泰金控為臺灣服務客戶數最多的領先金融服務業者，並致力於成為亞洲最佳金融機構。國泰世華銀行為...,工作經驗:3年以上學歷要求:大學以上科系要求:資訊工程相關語文條件英文(聽:中等、說:中等、...,臺北市,面議（經常性薪資達4萬元）,"軟體設計工程師, 產品管理師, 其他工程研發主管"

In [5]:
# 中英分離

demand = test.filter(['職缺名稱','標籤','工作內容'])

# 创建一个新的DataFrame来存放拆分后的行
new_rows = []

# 遍历原始DataFrame
for index, row in demand.iterrows():
    job_titles = row['職缺名稱'].split('、')
    jobName = row['標籤']
    JD = row['工作內容']
    for title in job_titles:
        new_row = {'職稱': title, '標籤': jobName, '職缺描述':JD}
        new_rows.append(new_row)

# 创建包含新行的新DataFrame
new_demand = pd.DataFrame(new_rows)

# data_duty = ['數據分析師','資料科學家','資料工程師','AI工程師','演算法工程師']
# mask = new_demand['職務'].isin(data_duty)
# new_demand = new_demand[mask]

# 將 工作敘述 的網址取代掉
def remove_url_and_html(text):
    # 用 re 取代 URL
    text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', text)
    
    # 用 re 移除 HTML tag
    text = re.sub(r'<.*?>', '', text)
    text = text.replace('\n', '').replace('\r', '').replace('\t', '')
    
    return text

# use re to replace html entities
def replace_html_entities(text):
    
    text = re.sub(r'<.*?>', '', text)
    
    # parse entities
    text = html.unescape(text)
    
    return text

new_demand['職缺描述'] = new_demand['職缺描述'].apply(remove_url_and_html)
new_demand['職缺描述'] = new_demand['職缺描述'].apply(replace_html_entities)

# 中英文 分離
# 提取中文
def extract_chinese(text):
    chinese_pattern = r'[\u4e00-\u9fa5]+'  # 中文字符
    chinese_matches = re.findall(chinese_pattern, text)
    return ' '.join(chinese_matches)  # 將多個中文字符，以空格分隔

# 提取英文
def extract_english(text):
    english_pattern = r'[a-zA-Z]+'  # 英文字符
    english_matches = re.findall(english_pattern, text)
    return ' '.join(english_matches)  # 將多個英文字符，以空格分隔

new_demand['職缺描述（中文）'] = new_demand['職缺描述'].apply(extract_chinese)
new_demand['職缺描述（英文）'] = new_demand['職缺描述'].apply(extract_english)

new_demand

,職稱,標籤,職缺描述,職缺描述（中文）,職缺描述（英文）
0,資料科學家,"AI, Data Scientist, Statistics Analysis",中醫只有華人才能精確掌握，雖然目前還很低調，但我們能提供的產品價值是過往廠商都無法提供的。除...,中醫只有華人才能精確掌握 雖然目前還很低調 但我們能提供的產品價值是過往廠商都無法提供的 除...,Insight automated data pipelines
1,[總部] 機器學習主任工程師 Principal Engineer_0220*,"軟體開發, AI, 軟體設計工程師, 機器學習, 大數據, 演算法開發工程師",我們是集團的策略長室團隊，目前正在積極尋找Machine Learning 主任工程師 加入...,我們是集團的策略長室團隊 目前正在積極尋找 主任工程師 加入我們 你將負責 應用架構設計與實...,Machine Learning Gamania Data Center is an exp...
2,Backend Engineer (Python),-,【Please Apply Here】 are on a mission to spark ...,,Please Apply Here are on a mission to spark co...
3,AI 產品經理( Prompt Engineering/ Fine Tuning）,-,部門介紹The Pocket CompanyThe Pocket Company是Accuc...,部門介紹 是 的全新部門 我們正站在 科技的最前緣 致力於塑造數位行銷領域的未來 我們的主要...,The Pocket CompanyThe Pocket Company Accucrazy...
4,Data Engineer - Python,Data Engineer,作為數據工程師（Python），您將負責在我們的G123平台上設計和實施強大的數據流程，以確...,作為數據工程師 您將負責在我們的 平台上設計和實施強大的數據流程 以確保最佳的時效性 數據品...,Python G G G
5,NLP Research Scientist,NLP,作為自然語言處理（NLP）研究技術人員，您將負責在與工程團隊密切合作的同時實施自然語言處理技...,作為自然語言處理 研究技術人員 您將負責在與工程團隊密切合作的同時實施自然語言處理技術 隨著...,NLP G NLP
6,MLOps Engineer,MachineLearning,作為機器學習運維（MLOps）工程師，您將負責實現模型在生產系統中的自動化部署，以在G123...,作為機器學習運維 工程師 您將負責實現模型在生產系統中的自動化部署 以在 平台不斷擴展其遊戲...,MLOps G CI CD
7,Data Scientist,data s,作為數據科學家，您將負責基於我們的G123平台大數據，應用機器學習、統計分析和數據可視化技術...,作為數據科學家 您將負責基於我們的 平台大數據 應用機器學習 統計分析和數據可視化技術 結合...,G G
8,Prompt Engineer,Prompt,- 與人工智慧和數據科學團隊緊密合作，為AI語言模型（如GPT-4）或生成式AI模型（如St...,與人工智慧和數據科學團隊緊密合作 為 語言模型 如 或生成式 模型 如 和 創建和優化提示 ...,AI GPT AI Stable Diffusion Midjourney AI AI
9,CV Research Scientist,ComputerVision,作為計算機視覺研究技術人員，您將負責在我們的內部橫幅生成工具中實現諸如GAN或穩定擴散等新的...,作為計算機視覺研究技術人員 您將負責在我們的內部橫幅生成工具中實現諸如 或穩定擴散等新的計算...,GAN G
10,【R&D】資料科學工程師 (AI),"AI, Data Scientist, Data, 資料科學",1. 基於LLMs開發應用及聊天功能，設計並優化體驗內容2. 機器學習、深度學習或其他資料科...,基於 開發應用及聊天功能 設計並優化體驗內容 機器學習 深度學習或其他資料科學相關演算法 產...,LLMs
11,2023 Turing Plan 儲備AI科學家 百萬年薪 開放申請中！,"Python, AI, 人工智慧, 演算法開發工程師, 資料工程, 資料科學家",【你的薪資你決定，百萬Turing就是你】Turing Plan 矢志尋找最頂尖的人工智慧技...,你的薪資你決定 百萬 就是你 矢志尋找最頂尖的人工智慧技術菁英 以 技術研發 應用開發 為兩...,Turing Turing Plan AI AI Turing Plan AI Alan M...
12,Video/ Image Processing Engineer,"跨國團隊, APP, 設計產業, 文創",We are looking for a Video/Image Processing So...,,We are looking for a Video Image Processing So...
13,MLOps Engineer,"Python, MachineLearning, pytorch, tensorflow, ...","As a MLOps engineer, you will be responsible f...",,As a MLOps engineer you will be responsible fo...
14,【AI Team】資料科學家 Data Scientist,"Python, SQL, Data Scientist, DS",【Responsibilities】 1. Plan actionable research...,,Responsibilities Plan actionable research and ...
15,數據架構師 Data Architect,Data,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,MVP POC POC
16,BI Analyst_BI數據分析,"資訊平台, 遊戲產業, 網路","- Set up and execute extract, transformation a...",,Set up and execute extract transformation and ...
17,深度(機器)學習資料科學家(台中),"軟體設計工程師, 演算法開發工程師, 統計學研究員, 3年以上工作經驗, 學歷碩士",1. 深度學習資料分析運用於機器視覺2. 深度學習演算法研究3. 資料前處理：確認客戶需求及...,深度學習資料分析運用於機器視覺 深度學習演算法研究 資料前處理 確認客戶需求及資料來源彙整 ...,
18,Data Scientist,"MachineLearning, Data Scientist, ETL","About The Job:At BlueX, data drives our decisi...",,About The Job At BlueX data drives our decisio...
19,AI/CV Team Lead /Sr. Computer Vision Engineer ...,"新創, Python, 網路新創, 網路, C++",世界上沒有一個模型不能解決的問題。 如果有，那就再做一個。Authme 致力於提供最快速、安...,世界上沒有一個模型不能解決的問題 如果有 那就再做一個 致力於提供最快速 安全與便利的數位身...,Authme Authme App SaaS CNN RNN etc Authme Auth...
20,【AI Team】資深數據工程師 Senior Data Engineer,Data Engineer,【Responsibilities】1. Create and maintain optim...,,Responsibilities Create and maintain optimal d...
21,DBA資料庫管理師 (MSSQL/MySQL),"Fintech, MySQL, 行動支付, MsSQL, DBA",KeyResponsibilities1. Troubleshoot application...,,KeyResponsibilities Troubleshoot application d...
22,【TENG1402】Data Engineer,"SaaS, Data Engineer, ecommerce",At SHOPLINE we are working on very interesting...,,At SHOPLINE we are working on very interesting...
23,資深數據工程師 Senior Data Engineer,Data Engineer,我們是偉康科技智能團隊，專注解決金融領域的智能專家，持續精進並發展監理科技產品。團隊成員有智...,我們是偉康科技智能團隊 專注解決金融領域的智能專家 持續精進並發展監理科技產品 團隊成員有智...,PoC
24,數據解決方案架構師 Data Solution Architect,-,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,Proof of Concept POC Request For Proposal RFP POC
25,Machine Learning intern,"新創, Python, 軟體開發, AI, MachineLearning, DeepLea...",了解各IoT領域（太陽能、射出成型機、電腦數值控制工具機 等等）的痛點，應用 ＭＬ以最有效率...,了解各 領域 太陽能 射出成型機 電腦數值控制工具機 等等 的痛點 應用 以最有效率最有產值...,IoT AI ML label
26,系統分析師 System Analyst - Salesforce,"系統分析師, data analysis, System analysis, System ...",Greenpeace exists because this fragile earth d...,,Greenpeace exists because this fragile earth d...
27,AI工程師(街口金融科技),"Python, MachineLearning, DeepLearning, Convers...",街口集團旗下新創事業，致力於打造AI驅動的社交App，我們正在積極尋找有熱情的夥伴加入團隊，...,街口集團旗下新創事業 致力於打造 驅動的社交 我們正在積極尋找有熱情的夥伴加入團隊 辦公室文...,AI App Job Description OpenAI API App AI LLMs ...
28,生物資訊工程師,"AI, MachineLearning, Drug Discovery, Causal In...",作為生物資訊工程師，除熟悉組學資料處理分析外，應時時渴望新技術與知識，與AI團隊協作發展出獨...,作為生物資訊工程師 除熟悉組學資料處理分析外 應時時渴望新技術與知識 與 團隊協作發展出獨家...,AI AI AI AI Bioinformatic Analysis includingOm...
29,資料科學家 Data Scientist,"AI, MachineLearning, DeepLearning, Drug Discov...",作為資料科學家，需要對資料保有高度熱誠，能夠歸納與統整大量的資料，並從中萃取出精華，發現未察...,作為資料科學家 需要對資料保有高度熱誠 能夠歸納與統整大量的資料 並從中萃取出精華 發現未察...,Vizuro AI
30,台灣領頭自駕系統軟體新創 Senior Algorithm Engineer (SLAM),-,[About the role]We are looking for a talented ...,,About the role We are looking for a talented s...
31,Data Engineer 資料工程師,-,GoFreight 是快速成長的雲端國際物流 SaaS 新創公司，專注在利用科技翻轉國際物流...,是快速成長的雲端國際物流 新創公司 專注在利用科技翻轉國際物流產業的傳統文書作業 不同於絕大...,GoFreight SaaS GoFreight C GoFreight GoFreight...
32,數據工程師,"Data Engineer, 數據工程師",工作地點:台北 + 遠端🇹🇼+🏡想要在職業生涯中快速發展？不要找工作！選擇一家公司，釋放你的...,工作地點 台北 遠端 想要在職業生涯中快速發展 不要找工作 選擇一家公司 釋放你的潛力 是由...,Aloha Group Limited Incu App Incu Tech LEAP Al...
33,"資深數據工程師 Sr.Data Engineer (AI Team, 台北/嘉義/東京)","Python, BigData, Linux, GCP, kubernetes, K8s",awoo 株式會社 (awoo Japan Inc.) 的成員來自世界各地，我們正在招募對深...,株式會社 的成員來自世界各地 我們正在招募對深度研發 技術和對台灣充滿熱情的夥伴加入我們 團...,awoo awoo Japan Inc AI AI AI AI Major Duties a...
34,AI / 機器學習工程師,"Python, AI, MachineLearning, DeepLearning",作為AI/機器學習工程師，須掌握各式的AI技術，並提供穩定且可靠的AI模型給使用者，也應隨時...,作為 機器學習工程師 須掌握各式的 技術 並提供穩定且可靠的 模型給使用者 也應隨時吸收新知...,AI AI AI Vizuro AI AI AI AI AI SOTA AI AI ML DL
35,Data Scientist,"Python, AI, Linux, MachineLearning, Data Scien...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...
36,Senior Machine Learning Engineer,"Python, AI, BigData, MachineLearning, DeepLear...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...
37,Senior Machine Learning Engineer 資深機器學習工程師,-,"▍About AlfredCameraFrom day one, we’ve been gu...",,About AlfredCameraFrom day one we ve been guid...
38,Data Engineer｜資料工程師,"Data Engineer, data analysis, System analysis",◆THE ROLE & THE TEAMAs a Data Engineer in JKOP...,,THE ROLE THE TEAMAs a Data Engineer in JKOPay ...
39,(2023實習) Machine Learning Engineer (時薪260）(可視訊...,"Python, AI, Java, BigData, MachineLearning",***歡迎身心障礙朋友投遞履歷***NetBase Quid is searching fo...,歡迎身心障礙朋友投遞履歷,NetBase Quid is searching for a talented and p...
40,資料科學工程師 (Kubernetes K8s 平台產品開發) -- 資料科學實驗室 (數...,"Git, K8s, Python Developer, R&D, openshift, ku...",我們 資料科學實驗室 的文化- 我們樂於互相分享，也樂於互相學習- 我們有主動發現問題，主動...,我們 資料科學實驗室 的文化 我們樂於互相分享 也樂於互相學習 我們有主動發現問題 主動解決...,K s container Hadoop K s container K s container
41,"資料科學工程師 (Data Engineer) -- 資料科學實驗室 (數數發中心, DDT)",-,職務包含但不限於以下內容- 基於 Python 語言之產品開發，推廣及後續維護- Docke...,職務包含但不限於以下內容 基於 語言之產品開發 推廣及後續維護 相關技術應用研發 雲端技術應...,Python Docker Kubernetes
42,【跨境電商物流系統】AI Engineer/ AI 工程師,"AI, MachineLearning, NLP",【職務情況說明】Return Helper為跨境電商逆物流服務商，自行開發倉儲逆物流/退貨平...,職務情況說明 為跨境電商逆物流服務商 自行開發倉儲逆物流 退貨平台系統提供台灣及全球賣家使用...,Return Helper UIUX Responsibilities NLP AI Qua...
43,【數位驅動】資料科學工程師_ 數據管理,"軟體設計工程師, 其他資訊專業人員, 資料庫管理人員",【主要職責 Who we are looking for】資料倉儲、資料市集設計及管理之ET...,主要職責 資料倉儲 資料市集設計及管理之 開發維運及批次監控 包含 銀行資料倉儲維運 相關 ...,Who we are looking for ETL AP What will you do...
44,【運籌管理中心】MES開發工程師,"MES, 鼎新",1.負責生產、物流相關MES系統規劃、開發、與維護作業。2.資料分析、設計與製作相關管理報表...,負責生產 物流相關 系統規劃 開發 與維護作業 資料分析 設計與製作相關管理報表 協助各項生...,MES
45,【資通訊整合中心】ERP工程師,"營運管理師／系統整合／ERP專案, 鼎新",1.維護鼎新 COSMOS ERP系統。2.維護鼎新 EasyFlow 電子表單系統。3.開...,維護鼎新 系統 維護鼎新 電子表單系統 開發報表模組及 程式 需求蒐集與分析 提出導入評估與建議,COSMOS ERP EasyFlow Web
46,資料工程師 Data Engineer (台中),Data Engineer,【】與產品團隊和前後端工程團隊合作，確保資料品質與產出1. 創建與維護Data Infras...,與產品團隊和前後端工程團隊合作 確保資料品質與產出 創建與維護 開發與維護,Data Infrastructure Data Pipeline ETL ELT Data...
47,<CCoE>Cloud Strategy Lead | CBU_13_01,-,【Job Description】We are EXCITED to announce th...,,Job Description We are EXCITED to announce tha...
48,<Data Team> Data Engineer 資料工程師| CBU_12_01,"數據分析, Data Engineer, 資料工程",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...
49,<Data Team> Machine Learning Engineer 機器學習工程師...,"MachineLearning, 機器學習",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...
50,香港上市醫學美容集團 AI Engineer/Specialist,-,運用Machine Learning、Deep Learning、統計與作業研究等技術來開發...,運用 統計與作業研究等技術來開發和維護 應用程序 並與團隊密切合作以實現公司的戰略目標研究新...,Machine Learning Deep Learning AI AI LLM GPT A...
51,香港上市醫學美容集團 Data Engineer,-,We are currently looking to recruit an enthusi...,,We are currently looking to recruit an enthusi...
52,107 資料分析/數據工程師(可遠端工作),"Python, AI, SQL, Java, C#, Spark",聽過黑盒子、演算法、機器學習、Alphago嗎？這些讓我們聯想到AI的代名詞是否讓你躍躍欲試...,聽過黑盒子 演算法 機器學習 嗎 這些讓我們聯想到 的代名詞是否讓你躍躍欲試 所綻放的魔力吸...,Alphago AI AI SQL Python R SPARK Java HTML C I...
53,Machine Learning Engineer,"MachineLearning, 軟體設計工程師, pytorch, tensorflow,...",1. Use Deep Learning techniques to solve compu...,,Use Deep Learning techniques to solve computer...
54,數據科學家,"Data Scientist, 資料科學, 數據科學家",我們正在和團隊成員一起開發一個系統，該系統將結合機器學習模型，自動生成用於尚平或服務廣告的文...,我們正在和團隊成員一起開發一個系統 該系統將結合機器學習模型 自動生成用於尚平或服務廣告的文...,
55,"【數位金融】資料科學分析師-數據分析 (數數發中心,DDT)","系統分析師, 演算法開發工程師, 統計學研究員",【職務說明 What will you do】1. 機器學習、深度學習或統計分析模型專案開發...,職務說明 機器學習 深度學習或統計分析模型專案開發 配合數據技術發展目標 研究與實作可落地應...,What will you do end to end
56,【數位金融】資料營運工程師(Hadoop),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責Hadoop大數據平台的運...,主要職責 你將負責 大數據平台的運維工作 建立自動化流程及標準作業程序 以提升 大數據平台擴...,Who we are looking for Hadoop Hadoop What will...
57,【數位金融】資料營運工程師(SRE),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責數據服務平台的運維工作，建...,主要職責 你將負責數據服務平台的運維工作 建立自動化流程及標準作業程序 以提升數據服務平台擴...,Who we are looking for What will you do OKD SOP
58,"【數位金融】數據策略規劃師(數數發中心, DDT)","市場調查／市場分析, 專案管理主管, 顧問人員",【職務說明 What will you do】1. 規劃新數據及新技術導入策略並設計對應商業...,職務說明 規劃新數據及新技術導入策略並設計對應商業場景推動落地實行 跨集團 跨部門溝通協調 ...,What will you do
59,【數位金融】Java 開發工程師/Java Engineer(數數發中心，DDT),"軟體設計工程師, 產品管理師, 其他工程研發主管",國泰金控為臺灣服務客戶數最多的領先金融服務業者，並致力於成為亞洲最佳金融機構。國泰世華銀行為...,國泰金控為臺灣服務客戶數最多的領先金融服務業者 並致力於成為亞洲最佳金融機構 國泰世華銀行為...,What you will do KOKO Scrum Team PM App Sprint...

In [6]:
# 分五大類
data_dict = {'NLP工程師':'自然語言|NLP|nlp|LLM|語言模型',
             '資料工程師':'ETL|Data Engineer|數據工程|Data Pipeline|倉儲|Hadoop',
             '資料科學家':'Data Scientist|深度學習|影像辨識|電腦視覺|人工智慧|AI|Deep Learning|影像處理|時間序列|Time Series|數據建模|資料科學|機器學習|ComputerVision|Computer Vision|Image Processing|MLOps|Machine Learning',
             '演算法工程師':'演算法|Algorithm|算法開發|算法設計',
             '數據分析師':'資料分析|商業數據分析|BI|Business Intelligence|商業分析|數據|Data Analyst'}

#############   
# def categorize_data(df, data_dict, label_column_name, tag_column_name):
#     # 創建一個新的標籤欄位
#     df[tag_column_name] = ""

#     # 對每個類別和相關的標籤執行分類
#     for category, keywords in data_dict.items():
#         for keyword in keywords.split('|'):
#             # 使用正則表達式檢查是否有包含關鍵字
#             df.loc[df[label_column_name].str.contains(keyword, case=False, regex=True), tag_column_name] = category

#     return df


# df = pd.DataFrame(data)
# result_df = categorize_data(PB_data_df_test, data_dict, '個人整體標籤', 'tag')
# result_df
############# 

def categorize_data(df, category_dict, label_column_names, tag_column_name):
    # 創建一個新的標籤欄位
    df[tag_column_name] = ""

    # 對每一行執行分類
    def categorize_row(row):
        for label_column_name in label_column_names:
            for category, keywords in category_dict.items():
                for keyword in keywords.split('|'):
                    # 使用正則表達式檢查是否有包含關鍵字
                    if pd.notna(row[label_column_name]) and re.search(keyword, row[label_column_name], re.IGNORECASE):
                        return category
        return ""

    # 將分類標籤應用於每一行
    df[tag_column_name] = df.apply(categorize_row, axis=1)

    return df

# classify each job with duty
label_column_names = ['標籤', '職稱', '職缺描述']
result_df = categorize_data(new_demand, data_dict, label_column_names, '職務')
result_df

,職稱,標籤,職缺描述,職缺描述（中文）,職缺描述（英文）,職務
0,資料科學家,"AI, Data Scientist, Statistics Analysis",中醫只有華人才能精確掌握，雖然目前還很低調，但我們能提供的產品價值是過往廠商都無法提供的。除...,中醫只有華人才能精確掌握 雖然目前還很低調 但我們能提供的產品價值是過往廠商都無法提供的 除...,Insight automated data pipelines,資料科學家
1,[總部] 機器學習主任工程師 Principal Engineer_0220*,"軟體開發, AI, 軟體設計工程師, 機器學習, 大數據, 演算法開發工程師",我們是集團的策略長室團隊，目前正在積極尋找Machine Learning 主任工程師 加入...,我們是集團的策略長室團隊 目前正在積極尋找 主任工程師 加入我們 你將負責 應用架構設計與實...,Machine Learning Gamania Data Center is an exp...,資料科學家
2,Backend Engineer (Python),-,【Please Apply Here】 are on a mission to spark ...,,Please Apply Here are on a mission to spark co...,資料工程師
3,AI 產品經理( Prompt Engineering/ Fine Tuning）,-,部門介紹The Pocket CompanyThe Pocket Company是Accuc...,部門介紹 是 的全新部門 我們正站在 科技的最前緣 致力於塑造數位行銷領域的未來 我們的主要...,The Pocket CompanyThe Pocket Company Accucrazy...,資料科學家
4,Data Engineer - Python,Data Engineer,作為數據工程師（Python），您將負責在我們的G123平台上設計和實施強大的數據流程，以確...,作為數據工程師 您將負責在我們的 平台上設計和實施強大的數據流程 以確保最佳的時效性 數據品...,Python G G G,資料工程師
5,NLP Research Scientist,NLP,作為自然語言處理（NLP）研究技術人員，您將負責在與工程團隊密切合作的同時實施自然語言處理技...,作為自然語言處理 研究技術人員 您將負責在與工程團隊密切合作的同時實施自然語言處理技術 隨著...,NLP G NLP,NLP工程師
6,MLOps Engineer,MachineLearning,作為機器學習運維（MLOps）工程師，您將負責實現模型在生產系統中的自動化部署，以在G123...,作為機器學習運維 工程師 您將負責實現模型在生產系統中的自動化部署 以在 平台不斷擴展其遊戲...,MLOps G CI CD,資料科學家
7,Data Scientist,data s,作為數據科學家，您將負責基於我們的G123平台大數據，應用機器學習、統計分析和數據可視化技術...,作為數據科學家 您將負責基於我們的 平台大數據 應用機器學習 統計分析和數據可視化技術 結合...,G G,資料科學家
8,Prompt Engineer,Prompt,- 與人工智慧和數據科學團隊緊密合作，為AI語言模型（如GPT-4）或生成式AI模型（如St...,與人工智慧和數據科學團隊緊密合作 為 語言模型 如 或生成式 模型 如 和 創建和優化提示 ...,AI GPT AI Stable Diffusion Midjourney AI AI,NLP工程師
9,CV Research Scientist,ComputerVision,作為計算機視覺研究技術人員，您將負責在我們的內部橫幅生成工具中實現諸如GAN或穩定擴散等新的...,作為計算機視覺研究技術人員 您將負責在我們的內部橫幅生成工具中實現諸如 或穩定擴散等新的計算...,GAN G,資料科學家
10,【R&D】資料科學工程師 (AI),"AI, Data Scientist, Data, 資料科學",1. 基於LLMs開發應用及聊天功能，設計並優化體驗內容2. 機器學習、深度學習或其他資料科...,基於 開發應用及聊天功能 設計並優化體驗內容 機器學習 深度學習或其他資料科學相關演算法 產...,LLMs,資料科學家
11,2023 Turing Plan 儲備AI科學家 百萬年薪 開放申請中！,"Python, AI, 人工智慧, 演算法開發工程師, 資料工程, 資料科學家",【你的薪資你決定，百萬Turing就是你】Turing Plan 矢志尋找最頂尖的人工智慧技...,你的薪資你決定 百萬 就是你 矢志尋找最頂尖的人工智慧技術菁英 以 技術研發 應用開發 為兩...,Turing Turing Plan AI AI Turing Plan AI Alan M...,資料科學家
12,Video/ Image Processing Engineer,"跨國團隊, APP, 設計產業, 文創",We are looking for a Video/Image Processing So...,,We are looking for a Video Image Processing So...,資料科學家
13,MLOps Engineer,"Python, MachineLearning, pytorch, tensorflow, ...","As a MLOps engineer, you will be responsible f...",,As a MLOps engineer you will be responsible fo...,資料科學家
14,【AI Team】資料科學家 Data Scientist,"Python, SQL, Data Scientist, DS",【Responsibilities】 1. Plan actionable research...,,Responsibilities Plan actionable research and ...,資料科學家
15,數據架構師 Data Architect,Data,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,MVP POC POC,數據分析師
16,BI Analyst_BI數據分析,"資訊平台, 遊戲產業, 網路","- Set up and execute extract, transformation a...",,Set up and execute extract transformation and ...,數據分析師
17,深度(機器)學習資料科學家(台中),"軟體設計工程師, 演算法開發工程師, 統計學研究員, 3年以上工作經驗, 學歷碩士",1. 深度學習資料分析運用於機器視覺2. 深度學習演算法研究3. 資料前處理：確認客戶需求及...,深度學習資料分析運用於機器視覺 深度學習演算法研究 資料前處理 確認客戶需求及資料來源彙整 ...,,演算法工程師
18,Data Scientist,"MachineLearning, Data Scientist, ETL","About The Job:At BlueX, data drives our decisi...",,About The Job At BlueX data drives our decisio...,資料工程師
19,AI/CV Team Lead /Sr. Computer Vision Engineer ...,"新創, Python, 網路新創, 網路, C++",世界上沒有一個模型不能解決的問題。 如果有，那就再做一個。Authme 致力於提供最快速、安...,世界上沒有一個模型不能解決的問題 如果有 那就再做一個 致力於提供最快速 安全與便利的數位身...,Authme Authme App SaaS CNN RNN etc Authme Auth...,資料科學家
20,【AI Team】資深數據工程師 Senior Data Engineer,Data Engineer,【Responsibilities】1. Create and maintain optim...,,Responsibilities Create and maintain optimal d...,資料工程師
21,DBA資料庫管理師 (MSSQL/MySQL),"Fintech, MySQL, 行動支付, MsSQL, DBA",KeyResponsibilities1. Troubleshoot application...,,KeyResponsibilities Troubleshoot application d...,資料工程師
22,【TENG1402】Data Engineer,"SaaS, Data Engineer, ecommerce",At SHOPLINE we are working on very interesting...,,At SHOPLINE we are working on very interesting...,資料工程師
23,資深數據工程師 Senior Data Engineer,Data Engineer,我們是偉康科技智能團隊，專注解決金融領域的智能專家，持續精進並發展監理科技產品。團隊成員有智...,我們是偉康科技智能團隊 專注解決金融領域的智能專家 持續精進並發展監理科技產品 團隊成員有智...,PoC,資料工程師
24,數據解決方案架構師 Data Solution Architect,-,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,Proof of Concept POC Request For Proposal RFP POC,數據分析師
25,Machine Learning intern,"新創, Python, 軟體開發, AI, MachineLearning, DeepLea...",了解各IoT領域（太陽能、射出成型機、電腦數值控制工具機 等等）的痛點，應用 ＭＬ以最有效率...,了解各 領域 太陽能 射出成型機 電腦數值控制工具機 等等 的痛點 應用 以最有效率最有產值...,IoT AI ML label,資料科學家
26,系統分析師 System Analyst - Salesforce,"系統分析師, data analysis, System analysis, System ...",Greenpeace exists because this fragile earth d...,,Greenpeace exists because this fragile earth d...,資料科學家
27,AI工程師(街口金融科技),"Python, MachineLearning, DeepLearning, Convers...",街口集團旗下新創事業，致力於打造AI驅動的社交App，我們正在積極尋找有熱情的夥伴加入團隊，...,街口集團旗下新創事業 致力於打造 驅動的社交 我們正在積極尋找有熱情的夥伴加入團隊 辦公室文...,AI App Job Description OpenAI API App AI LLMs ...,資料科學家
28,生物資訊工程師,"AI, MachineLearning, Drug Discovery, Causal In...",作為生物資訊工程師，除熟悉組學資料處理分析外，應時時渴望新技術與知識，與AI團隊協作發展出獨...,作為生物資訊工程師 除熟悉組學資料處理分析外 應時時渴望新技術與知識 與 團隊協作發展出獨家...,AI AI AI AI Bioinformatic Analysis includingOm...,資料科學家
29,資料科學家 Data Scientist,"AI, MachineLearning, DeepLearning, Drug Discov...",作為資料科學家，需要對資料保有高度熱誠，能夠歸納與統整大量的資料，並從中萃取出精華，發現未察...,作為資料科學家 需要對資料保有高度熱誠 能夠歸納與統整大量的資料 並從中萃取出精華 發現未察...,Vizuro AI,資料科學家
30,台灣領頭自駕系統軟體新創 Senior Algorithm Engineer (SLAM),-,[About the role]We are looking for a talented ...,,About the role We are looking for a talented s...,演算法工程師
31,Data Engineer 資料工程師,-,GoFreight 是快速成長的雲端國際物流 SaaS 新創公司，專注在利用科技翻轉國際物流...,是快速成長的雲端國際物流 新創公司 專注在利用科技翻轉國際物流產業的傳統文書作業 不同於絕大...,GoFreight SaaS GoFreight C GoFreight GoFreight...,資料工程師
32,數據工程師,"Data Engineer, 數據工程師",工作地點:台北 + 遠端🇹🇼+🏡想要在職業生涯中快速發展？不要找工作！選擇一家公司，釋放你的...,工作地點 台北 遠端 想要在職業生涯中快速發展 不要找工作 選擇一家公司 釋放你的潛力 是由...,Aloha Group Limited Incu App Incu Tech LEAP Al...,資料工程師
33,"資深數據工程師 Sr.Data Engineer (AI Team, 台北/嘉義/東京)","Python, BigData, Linux, GCP, kubernetes, K8s",awoo 株式會社 (awoo Japan Inc.) 的成員來自世界各地，我們正在招募對深...,株式會社 的成員來自世界各地 我們正在招募對深度研發 技術和對台灣充滿熱情的夥伴加入我們 團...,awoo awoo Japan Inc AI AI AI AI Major Duties a...,數據分析師
34,AI / 機器學習工程師,"Python, AI, MachineLearning, DeepLearning",作為AI/機器學習工程師，須掌握各式的AI技術，並提供穩定且可靠的AI模型給使用者，也應隨時...,作為 機器學習工程師 須掌握各式的 技術 並提供穩定且可靠的 模型給使用者 也應隨時吸收新知...,AI AI AI Vizuro AI AI AI AI AI SOTA AI AI ML DL,資料科學家
35,Data Scientist,"Python, AI, Linux, MachineLearning, Data Scien...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...,資料科學家
36,Senior Machine Learning Engineer,"Python, AI, BigData, MachineLearning, DeepLear...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...,資料科學家
37,Senior Machine Learning Engineer 資深機器學習工程師,-,"▍About AlfredCameraFrom day one, we’ve been gu...",,About AlfredCameraFrom day one we ve been guid...,資料科學家
38,Data Engineer｜資料工程師,"Data Engineer, data analysis, System analysis",◆THE ROLE & THE TEAMAs a Data Engineer in JKOP...,,THE ROLE THE TEAMAs a Data Engineer in JKOPay ...,資料工程師
39,(2023實習) Machine Learning Engineer (時薪260）(可視訊...,"Python, AI, Java, BigData, MachineLearning",***歡迎身心障礙朋友投遞履歷***NetBase Quid is searching fo...,歡迎身心障礙朋友投遞履歷,NetBase Quid is searching for a talented and p...,資料科學家
40,資料科學工程師 (Kubernetes K8s 平台產品開發) -- 資料科學實驗室 (數...,"Git, K8s, Python Developer, R&D, openshift, ku...",我們 資料科學實驗室 的文化- 我們樂於互相分享，也樂於互相學習- 我們有主動發現問題，主動...,我們 資料科學實驗室 的文化 我們樂於互相分享 也樂於互相學習 我們有主動發現問題 主動解決...,K s container Hadoop K s container K s container,資料科學家
41,"資料科學工程師 (Data Engineer) -- 資料科學實驗室 (數數發中心, DDT)",-,職務包含但不限於以下內容- 基於 Python 語言之產品開發，推廣及後續維護- Docke...,職務包含但不限於以下內容 基於 語言之產品開發 推廣及後續維護 相關技術應用研發 雲端技術應...,Python Docker Kubernetes,資料工程師
42,【跨境電商物流系統】AI Engineer/ AI 工程師,"AI, MachineLearning, NLP",【職務情況說明】Return Helper為跨境電商逆物流服務商，自行開發倉儲逆物流/退貨平...,職務情況說明 為跨境電商逆物流服務商 自行開發倉儲逆物流 退貨平台系統提供台灣及全球賣家使用...,Return Helper UIUX Responsibilities NLP AI Qua...,NLP工程師
43,【數位驅動】資料科學工程師_ 數據管理,"軟體設計工程師, 其他資訊專業人員, 資料庫管理人員",【主要職責 Who we are looking for】資料倉儲、資料市集設計及管理之ET...,主要職責 資料倉儲 資料市集設計及管理之 開發維運及批次監控 包含 銀行資料倉儲維運 相關 ...,Who we are looking for ETL AP What will you do...,資料科學家
44,【運籌管理中心】MES開發工程師,"MES, 鼎新",1.負責生產、物流相關MES系統規劃、開發、與維護作業。2.資料分析、設計與製作相關管理報表...,負責生產 物流相關 系統規劃 開發 與維護作業 資料分析 設計與製作相關管理報表 協助各項生...,MES,數據分析師
45,【資通訊整合中心】ERP工程師,"營運管理師／系統整合／ERP專案, 鼎新",1.維護鼎新 COSMOS ERP系統。2.維護鼎新 EasyFlow 電子表單系統。3.開...,維護鼎新 系統 維護鼎新 電子表單系統 開發報表模組及 程式 需求蒐集與分析 提出導入評估與建議,COSMOS ERP EasyFlow Web,
46,資料工程師 Data Engineer (台中),Data Engineer,【】與產品團隊和前後端工程團隊合作，確保資料品質與產出1. 創建與維護Data Infras...,與產品團隊和前後端工程團隊合作 確保資料品質與產出 創建與維護 開發與維護,Data Infrastructure Data Pipeline ETL ELT Data...,資料工程師
47,<CCoE>Cloud Strategy Lead | CBU_13_01,-,【Job Description】We are EXCITED to announce th...,,Job Description We are EXCITED to announce tha...,資料科學家
48,<Data Team> Data Engineer 資料工程師| CBU_12_01,"數據分析, Data Engineer, 資料工程",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...,資料工程師
49,<Data Team> Machine Learning Engineer 機器學習工程師...,"MachineLearning, 機器學習",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...,資料科學家
50,香港上市醫學美容集團 AI Engineer/Specialist,-,運用Machine Learning、Deep Learning、統計與作業研究等技術來開發...,運用 統計與作業研究等技術來開發和維護 應用程序 並與團隊密切合作以實現公司的戰略目標研究新...,Machine Learning Deep Learning AI AI LLM GPT A...,資料科學家
51,香港上市醫學美容集團 Data Engineer,-,We are currently looking to recruit an enthusi...,,We are currently looking to recruit an enthusi...,資料工程師
52,107 資料分析/數據工程師(可遠端工作),"Python, AI, SQL, Java, C#, Spark",聽過黑盒子、演算法、機器學習、Alphago嗎？這些讓我們聯想到AI的代名詞是否讓你躍躍欲試...,聽過黑盒子 演算法 機器學習 嗎 這些讓我們聯想到 的代名詞是否讓你躍躍欲試 所綻放的魔力吸...,Alphago AI AI SQL Python R SPARK Java HTML C I...,資料科學家
53,Machine Learning Engineer,"MachineLearning, 軟體設計工程師, pytorch, tensorflow,...",1. Use Deep Learning techniques to solve compu...,,Use Deep Learning techniques to solve computer...,資料科學家
54,數據科學家,"Data Scientist, 資料科學, 數據科學家",我們正在和團隊成員一起開發一個系統，該系統將結合機器學習模型，自動生成用於尚平或服務廣告的文...,我們正在和團隊成員一起開發一個系統 該系統將結合機器學習模型 自動生成用於尚平或服務廣告的文...,,資料科學家
55,"【數位金融】資料科學分析師-數據分析 (數數發中心,DDT)","系統分析師, 演算法開發工程師, 統計學研究員",【職務說明 What will you do】1. 機器學習、深度學習或統計分析模型專案開發...,職務說明 機器學習 深度學習或統計分析模型專案開發 配合數據技術發展目標 研究與實作可落地應...,What will you do end to end,演算法工程師
56,【數位金融】資料營運工程師(Hadoop),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責Hadoop大數據平台的運...,主要職責 你將負責 大數據平台的運維工作 建立自動化流程及標準作業程序 以提升 大數據平台擴...,Who we are looking for Hadoop Hadoop What will...,資料工程師
57,【數位金融】資料營運工程師(SRE),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責數據服務平台的運維工作，建...,主要職責 你將負責數據服務平台的運維工作 建立自動化流程及標準作業程序 以提升數據服務平台擴...,Who we are looking for What will you do OKD SOP,數據分析師
58,"【數位金融】數據策略規劃師(數數發中心, DDT)","市場調查／市場分析, 專案管理主管, 顧問人員",【職務說明 What will you do】1. 規劃新數據及新技術導入策略並設計對應商業...,職務說明 規劃新數據及新技術導入策略並設計對應商業場景推動落地實行 跨集團 跨部門溝通協調 ...,What will you do,數據分析師
59,【數位金融】Java 開發工程師/Java Engineer(數數發中心，DDT),"軟體設計工程師, 產品管理師, 其他工程研發主管",國泰金控為臺灣服務客戶數最多的領先金融服務業者，並致力於成為亞洲最佳金融機構。國泰世華銀行為...,國泰金控為臺灣服務客戶數最多的領先金融服務業者 並致力於成為亞洲最佳金融機構 國泰世華銀行為...,What you will do KOKO Scrum Team PM App Sprint...,資料科學家

In [7]:
result_df = result_df[result_df['職務']!='']
result_df

,職稱,標籤,職缺描述,職缺描述（中文）,職缺描述（英文）,職務
0,資料科學家,"AI, Data Scientist, Statistics Analysis",中醫只有華人才能精確掌握，雖然目前還很低調，但我們能提供的產品價值是過往廠商都無法提供的。除...,中醫只有華人才能精確掌握 雖然目前還很低調 但我們能提供的產品價值是過往廠商都無法提供的 除...,Insight automated data pipelines,資料科學家
1,[總部] 機器學習主任工程師 Principal Engineer_0220*,"軟體開發, AI, 軟體設計工程師, 機器學習, 大數據, 演算法開發工程師",我們是集團的策略長室團隊，目前正在積極尋找Machine Learning 主任工程師 加入...,我們是集團的策略長室團隊 目前正在積極尋找 主任工程師 加入我們 你將負責 應用架構設計與實...,Machine Learning Gamania Data Center is an exp...,資料科學家
2,Backend Engineer (Python),-,【Please Apply Here】 are on a mission to spark ...,,Please Apply Here are on a mission to spark co...,資料工程師
3,AI 產品經理( Prompt Engineering/ Fine Tuning）,-,部門介紹The Pocket CompanyThe Pocket Company是Accuc...,部門介紹 是 的全新部門 我們正站在 科技的最前緣 致力於塑造數位行銷領域的未來 我們的主要...,The Pocket CompanyThe Pocket Company Accucrazy...,資料科學家
4,Data Engineer - Python,Data Engineer,作為數據工程師（Python），您將負責在我們的G123平台上設計和實施強大的數據流程，以確...,作為數據工程師 您將負責在我們的 平台上設計和實施強大的數據流程 以確保最佳的時效性 數據品...,Python G G G,資料工程師
5,NLP Research Scientist,NLP,作為自然語言處理（NLP）研究技術人員，您將負責在與工程團隊密切合作的同時實施自然語言處理技...,作為自然語言處理 研究技術人員 您將負責在與工程團隊密切合作的同時實施自然語言處理技術 隨著...,NLP G NLP,NLP工程師
6,MLOps Engineer,MachineLearning,作為機器學習運維（MLOps）工程師，您將負責實現模型在生產系統中的自動化部署，以在G123...,作為機器學習運維 工程師 您將負責實現模型在生產系統中的自動化部署 以在 平台不斷擴展其遊戲...,MLOps G CI CD,資料科學家
7,Data Scientist,data s,作為數據科學家，您將負責基於我們的G123平台大數據，應用機器學習、統計分析和數據可視化技術...,作為數據科學家 您將負責基於我們的 平台大數據 應用機器學習 統計分析和數據可視化技術 結合...,G G,資料科學家
8,Prompt Engineer,Prompt,- 與人工智慧和數據科學團隊緊密合作，為AI語言模型（如GPT-4）或生成式AI模型（如St...,與人工智慧和數據科學團隊緊密合作 為 語言模型 如 或生成式 模型 如 和 創建和優化提示 ...,AI GPT AI Stable Diffusion Midjourney AI AI,NLP工程師
9,CV Research Scientist,ComputerVision,作為計算機視覺研究技術人員，您將負責在我們的內部橫幅生成工具中實現諸如GAN或穩定擴散等新的...,作為計算機視覺研究技術人員 您將負責在我們的內部橫幅生成工具中實現諸如 或穩定擴散等新的計算...,GAN G,資料科學家
10,【R&D】資料科學工程師 (AI),"AI, Data Scientist, Data, 資料科學",1. 基於LLMs開發應用及聊天功能，設計並優化體驗內容2. 機器學習、深度學習或其他資料科...,基於 開發應用及聊天功能 設計並優化體驗內容 機器學習 深度學習或其他資料科學相關演算法 產...,LLMs,資料科學家
11,2023 Turing Plan 儲備AI科學家 百萬年薪 開放申請中！,"Python, AI, 人工智慧, 演算法開發工程師, 資料工程, 資料科學家",【你的薪資你決定，百萬Turing就是你】Turing Plan 矢志尋找最頂尖的人工智慧技...,你的薪資你決定 百萬 就是你 矢志尋找最頂尖的人工智慧技術菁英 以 技術研發 應用開發 為兩...,Turing Turing Plan AI AI Turing Plan AI Alan M...,資料科學家
12,Video/ Image Processing Engineer,"跨國團隊, APP, 設計產業, 文創",We are looking for a Video/Image Processing So...,,We are looking for a Video Image Processing So...,資料科學家
13,MLOps Engineer,"Python, MachineLearning, pytorch, tensorflow, ...","As a MLOps engineer, you will be responsible f...",,As a MLOps engineer you will be responsible fo...,資料科學家
14,【AI Team】資料科學家 Data Scientist,"Python, SQL, Data Scientist, DS",【Responsibilities】 1. Plan actionable research...,,Responsibilities Plan actionable research and ...,資料科學家
15,數據架構師 Data Architect,Data,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,MVP POC POC,數據分析師
16,BI Analyst_BI數據分析,"資訊平台, 遊戲產業, 網路","- Set up and execute extract, transformation a...",,Set up and execute extract transformation and ...,數據分析師
17,深度(機器)學習資料科學家(台中),"軟體設計工程師, 演算法開發工程師, 統計學研究員, 3年以上工作經驗, 學歷碩士",1. 深度學習資料分析運用於機器視覺2. 深度學習演算法研究3. 資料前處理：確認客戶需求及...,深度學習資料分析運用於機器視覺 深度學習演算法研究 資料前處理 確認客戶需求及資料來源彙整 ...,,演算法工程師
18,Data Scientist,"MachineLearning, Data Scientist, ETL","About The Job:At BlueX, data drives our decisi...",,About The Job At BlueX data drives our decisio...,資料工程師
19,AI/CV Team Lead /Sr. Computer Vision Engineer ...,"新創, Python, 網路新創, 網路, C++",世界上沒有一個模型不能解決的問題。 如果有，那就再做一個。Authme 致力於提供最快速、安...,世界上沒有一個模型不能解決的問題 如果有 那就再做一個 致力於提供最快速 安全與便利的數位身...,Authme Authme App SaaS CNN RNN etc Authme Auth...,資料科學家
20,【AI Team】資深數據工程師 Senior Data Engineer,Data Engineer,【Responsibilities】1. Create and maintain optim...,,Responsibilities Create and maintain optimal d...,資料工程師
21,DBA資料庫管理師 (MSSQL/MySQL),"Fintech, MySQL, 行動支付, MsSQL, DBA",KeyResponsibilities1. Troubleshoot application...,,KeyResponsibilities Troubleshoot application d...,資料工程師
22,【TENG1402】Data Engineer,"SaaS, Data Engineer, ecommerce",At SHOPLINE we are working on very interesting...,,At SHOPLINE we are working on very interesting...,資料工程師
23,資深數據工程師 Senior Data Engineer,Data Engineer,我們是偉康科技智能團隊，專注解決金融領域的智能專家，持續精進並發展監理科技產品。團隊成員有智...,我們是偉康科技智能團隊 專注解決金融領域的智能專家 持續精進並發展監理科技產品 團隊成員有智...,PoC,資料工程師
24,數據解決方案架構師 Data Solution Architect,-,我們是偉康科技數據團隊，專注解決金融領域數據專家，持續精進並發展監理科技產品。團隊成員有數據...,我們是偉康科技數據團隊 專注解決金融領域數據專家 持續精進並發展監理科技產品 團隊成員有數據...,Proof of Concept POC Request For Proposal RFP POC,數據分析師
25,Machine Learning intern,"新創, Python, 軟體開發, AI, MachineLearning, DeepLea...",了解各IoT領域（太陽能、射出成型機、電腦數值控制工具機 等等）的痛點，應用 ＭＬ以最有效率...,了解各 領域 太陽能 射出成型機 電腦數值控制工具機 等等 的痛點 應用 以最有效率最有產值...,IoT AI ML label,資料科學家
26,系統分析師 System Analyst - Salesforce,"系統分析師, data analysis, System analysis, System ...",Greenpeace exists because this fragile earth d...,,Greenpeace exists because this fragile earth d...,資料科學家
27,AI工程師(街口金融科技),"Python, MachineLearning, DeepLearning, Convers...",街口集團旗下新創事業，致力於打造AI驅動的社交App，我們正在積極尋找有熱情的夥伴加入團隊，...,街口集團旗下新創事業 致力於打造 驅動的社交 我們正在積極尋找有熱情的夥伴加入團隊 辦公室文...,AI App Job Description OpenAI API App AI LLMs ...,資料科學家
28,生物資訊工程師,"AI, MachineLearning, Drug Discovery, Causal In...",作為生物資訊工程師，除熟悉組學資料處理分析外，應時時渴望新技術與知識，與AI團隊協作發展出獨...,作為生物資訊工程師 除熟悉組學資料處理分析外 應時時渴望新技術與知識 與 團隊協作發展出獨家...,AI AI AI AI Bioinformatic Analysis includingOm...,資料科學家
29,資料科學家 Data Scientist,"AI, MachineLearning, DeepLearning, Drug Discov...",作為資料科學家，需要對資料保有高度熱誠，能夠歸納與統整大量的資料，並從中萃取出精華，發現未察...,作為資料科學家 需要對資料保有高度熱誠 能夠歸納與統整大量的資料 並從中萃取出精華 發現未察...,Vizuro AI,資料科學家
30,台灣領頭自駕系統軟體新創 Senior Algorithm Engineer (SLAM),-,[About the role]We are looking for a talented ...,,About the role We are looking for a talented s...,演算法工程師
31,Data Engineer 資料工程師,-,GoFreight 是快速成長的雲端國際物流 SaaS 新創公司，專注在利用科技翻轉國際物流...,是快速成長的雲端國際物流 新創公司 專注在利用科技翻轉國際物流產業的傳統文書作業 不同於絕大...,GoFreight SaaS GoFreight C GoFreight GoFreight...,資料工程師
32,數據工程師,"Data Engineer, 數據工程師",工作地點:台北 + 遠端🇹🇼+🏡想要在職業生涯中快速發展？不要找工作！選擇一家公司，釋放你的...,工作地點 台北 遠端 想要在職業生涯中快速發展 不要找工作 選擇一家公司 釋放你的潛力 是由...,Aloha Group Limited Incu App Incu Tech LEAP Al...,資料工程師
33,"資深數據工程師 Sr.Data Engineer (AI Team, 台北/嘉義/東京)","Python, BigData, Linux, GCP, kubernetes, K8s",awoo 株式會社 (awoo Japan Inc.) 的成員來自世界各地，我們正在招募對深...,株式會社 的成員來自世界各地 我們正在招募對深度研發 技術和對台灣充滿熱情的夥伴加入我們 團...,awoo awoo Japan Inc AI AI AI AI Major Duties a...,數據分析師
34,AI / 機器學習工程師,"Python, AI, MachineLearning, DeepLearning",作為AI/機器學習工程師，須掌握各式的AI技術，並提供穩定且可靠的AI模型給使用者，也應隨時...,作為 機器學習工程師 須掌握各式的 技術 並提供穩定且可靠的 模型給使用者 也應隨時吸收新知...,AI AI AI Vizuro AI AI AI AI AI SOTA AI AI ML DL,資料科學家
35,Data Scientist,"Python, AI, Linux, MachineLearning, Data Scien...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...,資料科學家
36,Senior Machine Learning Engineer,"Python, AI, BigData, MachineLearning, DeepLear...","1. Design, develop and implement machine learn...",,Design develop and implement machine learning ...,資料科學家
37,Senior Machine Learning Engineer 資深機器學習工程師,-,"▍About AlfredCameraFrom day one, we’ve been gu...",,About AlfredCameraFrom day one we ve been guid...,資料科學家
38,Data Engineer｜資料工程師,"Data Engineer, data analysis, System analysis",◆THE ROLE & THE TEAMAs a Data Engineer in JKOP...,,THE ROLE THE TEAMAs a Data Engineer in JKOPay ...,資料工程師
39,(2023實習) Machine Learning Engineer (時薪260）(可視訊...,"Python, AI, Java, BigData, MachineLearning",***歡迎身心障礙朋友投遞履歷***NetBase Quid is searching fo...,歡迎身心障礙朋友投遞履歷,NetBase Quid is searching for a talented and p...,資料科學家
40,資料科學工程師 (Kubernetes K8s 平台產品開發) -- 資料科學實驗室 (數...,"Git, K8s, Python Developer, R&D, openshift, ku...",我們 資料科學實驗室 的文化- 我們樂於互相分享，也樂於互相學習- 我們有主動發現問題，主動...,我們 資料科學實驗室 的文化 我們樂於互相分享 也樂於互相學習 我們有主動發現問題 主動解決...,K s container Hadoop K s container K s container,資料科學家
41,"資料科學工程師 (Data Engineer) -- 資料科學實驗室 (數數發中心, DDT)",-,職務包含但不限於以下內容- 基於 Python 語言之產品開發，推廣及後續維護- Docke...,職務包含但不限於以下內容 基於 語言之產品開發 推廣及後續維護 相關技術應用研發 雲端技術應...,Python Docker Kubernetes,資料工程師
42,【跨境電商物流系統】AI Engineer/ AI 工程師,"AI, MachineLearning, NLP",【職務情況說明】Return Helper為跨境電商逆物流服務商，自行開發倉儲逆物流/退貨平...,職務情況說明 為跨境電商逆物流服務商 自行開發倉儲逆物流 退貨平台系統提供台灣及全球賣家使用...,Return Helper UIUX Responsibilities NLP AI Qua...,NLP工程師
43,【數位驅動】資料科學工程師_ 數據管理,"軟體設計工程師, 其他資訊專業人員, 資料庫管理人員",【主要職責 Who we are looking for】資料倉儲、資料市集設計及管理之ET...,主要職責 資料倉儲 資料市集設計及管理之 開發維運及批次監控 包含 銀行資料倉儲維運 相關 ...,Who we are looking for ETL AP What will you do...,資料科學家
44,【運籌管理中心】MES開發工程師,"MES, 鼎新",1.負責生產、物流相關MES系統規劃、開發、與維護作業。2.資料分析、設計與製作相關管理報表...,負責生產 物流相關 系統規劃 開發 與維護作業 資料分析 設計與製作相關管理報表 協助各項生...,MES,數據分析師
46,資料工程師 Data Engineer (台中),Data Engineer,【】與產品團隊和前後端工程團隊合作，確保資料品質與產出1. 創建與維護Data Infras...,與產品團隊和前後端工程團隊合作 確保資料品質與產出 創建與維護 開發與維護,Data Infrastructure Data Pipeline ETL ELT Data...,資料工程師
47,<CCoE>Cloud Strategy Lead | CBU_13_01,-,【Job Description】We are EXCITED to announce th...,,Job Description We are EXCITED to announce tha...,資料科學家
48,<Data Team> Data Engineer 資料工程師| CBU_12_01,"數據分析, Data Engineer, 資料工程",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...,資料工程師
49,<Data Team> Machine Learning Engineer 機器學習工程師...,"MachineLearning, 機器學習",We are an ambitious Data Team Service Delivery...,,We are an ambitious Data Team Service Delivery...,資料科學家
50,香港上市醫學美容集團 AI Engineer/Specialist,-,運用Machine Learning、Deep Learning、統計與作業研究等技術來開發...,運用 統計與作業研究等技術來開發和維護 應用程序 並與團隊密切合作以實現公司的戰略目標研究新...,Machine Learning Deep Learning AI AI LLM GPT A...,資料科學家
51,香港上市醫學美容集團 Data Engineer,-,We are currently looking to recruit an enthusi...,,We are currently looking to recruit an enthusi...,資料工程師
52,107 資料分析/數據工程師(可遠端工作),"Python, AI, SQL, Java, C#, Spark",聽過黑盒子、演算法、機器學習、Alphago嗎？這些讓我們聯想到AI的代名詞是否讓你躍躍欲試...,聽過黑盒子 演算法 機器學習 嗎 這些讓我們聯想到 的代名詞是否讓你躍躍欲試 所綻放的魔力吸...,Alphago AI AI SQL Python R SPARK Java HTML C I...,資料科學家
53,Machine Learning Engineer,"MachineLearning, 軟體設計工程師, pytorch, tensorflow,...",1. Use Deep Learning techniques to solve compu...,,Use Deep Learning techniques to solve computer...,資料科學家
54,數據科學家,"Data Scientist, 資料科學, 數據科學家",我們正在和團隊成員一起開發一個系統，該系統將結合機器學習模型，自動生成用於尚平或服務廣告的文...,我們正在和團隊成員一起開發一個系統 該系統將結合機器學習模型 自動生成用於尚平或服務廣告的文...,,資料科學家
55,"【數位金融】資料科學分析師-數據分析 (數數發中心,DDT)","系統分析師, 演算法開發工程師, 統計學研究員",【職務說明 What will you do】1. 機器學習、深度學習或統計分析模型專案開發...,職務說明 機器學習 深度學習或統計分析模型專案開發 配合數據技術發展目標 研究與實作可落地應...,What will you do end to end,演算法工程師
56,【數位金融】資料營運工程師(Hadoop),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責Hadoop大數據平台的運...,主要職責 你將負責 大數據平台的運維工作 建立自動化流程及標準作業程序 以提升 大數據平台擴...,Who we are looking for Hadoop Hadoop What will...,資料工程師
57,【數位金融】資料營運工程師(SRE),"軟體設計工程師, 系統維護／操作人員, 資料庫管理人員",【主要職責 Who we are looking for】你將負責數據服務平台的運維工作，建...,主要職責 你將負責數據服務平台的運維工作 建立自動化流程及標準作業程序 以提升數據服務平台擴...,Who we are looking for What will you do OKD SOP,數據分析師
58,"【數位金融】數據策略規劃師(數數發中心, DDT)","市場調查／市場分析, 專案管理主管, 顧問人員",【職務說明 What will you do】1. 規劃新數據及新技術導入策略並設計對應商業...,職務說明 規劃新數據及新技術導入策略並設計對應商業場景推動落地實行 跨集團 跨部門溝通協調 ...,What will you do,數據分析師
59,【數位金融】Java 開發工程師/Java Engineer(數數發中心，DDT),"軟體設計工程師, 產品管理師, 其他工程研發主管",國泰金控為臺灣服務客戶數最多的領先金融服務業者，並致力於成為亞洲最佳金融機構。國泰世華銀行為...,國泰金控為臺灣服務客戶數最多的領先金融服務業者 並致力於成為亞洲最佳金融機構 國泰世華銀行為...,What you will do KOKO Scrum Team PM App Sprint...,資料科學家

In [8]:
category_counts = result_df['職務'].value_counts()
category_counts

資料科學家     31
資料工程師     15
數據分析師      7
NLP工程師     3
演算法工程師     3
Name: 職務, dtype: int64

In [9]:
result_df.to_excel('Yourator數據職缺JD_中英文分離_1004.xlsx', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
cd '/content/gdrive/My Drive/data'

In [ ]:
test.to_excel('Yourator.xlsx',index=False)